const vocabularyData = {
    greetings: [
        { mongolian: "Сайн уу", pronunciation: "Sain uu", english: "Hello", audio: "audio/Mots/lesson 1/hello.mp3" },
        { mongolian: "Сайн байна уу", pronunciation: "Sain baina uu", english: "How are you?", audio: "audio/Mots/lesson 1/how_are_you.mp3" },
        { mongolian: "Баярлалаа", pronunciation: "Bayarlalaa", english: "Thank you", audio: "audio/Mots/lesson 1/thank_you.mp3" },
        { mongolian: "Үгүй", pronunciation: "Ügüi", english: "No", audio: "audio/Mots/lesson 1/no.mp3" },
        { mongolian: "Тийм", pronunciation: "Tiim", english: "Yes", audio: "audio/Mots/lesson 1/yes.mp3" },
        { mongolian: "Сайн", pronunciation: "Sain", english: "Good", audio: "audio/Mots/lesson 1/good.mp3" },
        { mongolian: "Буруу", pronunciation: "Buruu", english: "Wrong", audio: "audio/Mots/lesson 1/wrong.mp3" },
        { mongolian: "Зөв", pronunciation: "Zöv", english: "Correct", audio: "audio/Mots/lesson 1/correct.mp3" },
        { mongolian: "Тавтай морил", pronunciation: "Tavtai moril", english: "Welcome", audio: "audio/Mots/lesson 1/welcome.mp3" },
        { mongolian: "Баяртай", pronunciation: "Bayartai", english: "Goodbye", audio: "audio/Mots/lesson 1/goodbye.mp3" },
        { mongolian: "Уучлаарай", pronunciation: "Uuchlaarai", english: "Sorry", audio: "audio/Mots/lesson 1/sorry.mp3" },
        { mongolian: "Ойлгосон", pronunciation: "Oilgoson", english: "Understood", audio: "audio/Mots/lesson 1/understood.mp3" },
        { mongolian: "Ойлгохгүй", pronunciation: "Oiloghui", english: "I don't understand", audio: "audio/Mots/lesson 1/i_dont_understand.mp3" },
        { mongolian: "Нэр", pronunciation: "Ner", english: "Name", audio: "audio/Mots/lesson 1/name.mp3" },
        { mongolian: "Би", pronunciation: "Bi", english: "I", audio: "audio/Mots/lesson 1/i.mp3" },
        { mongolian: "Чи", pronunciation: "Chi", english: "You", audio: "audio/Mots/lesson 1/you.mp3" },
        { mongolian: "Тэр", pronunciation: "Ter", english: "He/She", audio: "audio/Mots/lesson 1/he_she.mp3" },
        { mongolian: "Бид", pronunciation: "Bid", english: "We", audio: "audio/Mots/lesson 1/we.mp3" },
        { mongolian: "Та", pronunciation: "Ta", english: "Formal 'You'", audio: "audio/Mots/lesson 1/formal_you.mp3" },
        { mongolian: "Яах вэ", pronunciation: "Yaakh ve?", english: "What to do?", audio: "audio/Mots/lesson 1/what_to_do.mp3" }
    ],
    numbers: [
        { mongolian: "Нэг", pronunciation: "Neg", english: "One", audio: "audio/Mots/lesson 2/One.mp3" },
        { mongolian: "Хоёр", pronunciation: "Khoir", english: "Two", audio: "audio/Mots/lesson 2/Two.mp3" },
        { mongolian: "Гурав", pronunciation: "Gurav", english: "Three", audio: "audio/Mots/lesson 2/Three.mp3" },
        { mongolian: "Дөрөв", pronunciation: "Döröv", english: "Four", audio: "audio/Mots/lesson 2/Four.mp3" },
        { mongolian: "Тав", pronunciation: "Tav", english: "Five", audio: "audio/Mots/lesson 2/Five.mp3" },
        { mongolian: "Зургаа", pronunciation: "Zurgaa", english: "Six", audio: "audio/Mots/lesson 2/Six.mp3" },
        { mongolian: "Долоо", pronunciation: "Doloo", english: "Seven", audio: "audio/Mots/lesson 2/Seven.mp3" },
        { mongolian: "Найм", pronunciation: "Naim", english: "Eight", audio: "audio/Mots/lesson 2/Eight.mp3" },
        { mongolian: "Ес", pronunciation: "Yes", english: "Nine", audio: "audio/Mots/lesson 2/Nine.mp3" },
        { mongolian: "Арван", pronunciation: "Arvan", english: "Ten", audio: "audio/Mots/lesson 2/Ten.mp3" },
        { mongolian: "Цаг", pronunciation: "Tsag", english: "Time", audio: "audio/Mots/lesson 2/Time.mp3" },
        { mongolian: "Минут", pronunciation: "Minut", english: "Minute", audio: "audio/Mots/lesson 2/Minute.mp3" },
        { mongolian: "Өглөө", pronunciation: "Öglöö", english: "Morning", audio: "audio/Mots/lesson 2/Morning.mp3" },
        { mongolian: "Өдөр", pronunciation: "Ödör", english: "Day", audio: "audio/Mots/lesson 2/Day.mp3" },
        { mongolian: "Орой", pronunciation: "Oroi", english: "Evening", audio: "audio/Mots/lesson 2/Evening.mp3" },
        { mongolian: "Шөнө", pronunciation: "Shönö", english: "Night", audio: "audio/Mots/lesson 2/Night.mp3" },
        { mongolian: "Хугацаа", pronunciation: "Khugatsaa", english: "Duration", audio: "audio/Mots/lesson 2/Duration.mp3" },
        { mongolian: "Долоо хоног", pronunciation: "Doloo khonog", english: "Week", audio: "audio/Mots/lesson 2/Week.mp3" },
        { mongolian: "Сар", pronunciation: "Sar", english: "Month", audio: "audio/Mots/lesson 2/Month.mp3" },
        { mongolian: "Жил", pronunciation: "Jil", english: "Year", audio: "audio/Mots/lesson 2/Year.mp3" }
    ],
    family: [
        { mongolian: "Аав", pronunciation: "Aav", english: "Father", audio: "audio/Mots/lesson 3/Father.m4a" },
        { mongolian: "Ээж", pronunciation: "Eej", english: "Mother", audio: "audio/Mots/lesson 3/Mother.m4a" },
        { mongolian: "Ах", pronunciation: "Akh", english: "Older brother", audio: "audio/Mots/lesson 3/older_brother.m4a" },
        { mongolian: "Эгч", pronunciation: "Egch", english: "Older sister", audio: "audio/Mots/lesson 3/older_sister.m4a" },
        { mongolian: "Дүү", pronunciation: "Düü", english: "Younger sibling", audio: "audio/Mots/lesson 3/younger_sibling.m4a" },
        { mongolian: "Хүүхэд", pronunciation: "Khüükhed", english: "Child", audio: "audio/Mots/lesson 3/Child.m4a" },
        { mongolian: "Өвөө", pronunciation: "Övöö", english: "Grandfather", audio: "audio/Mots/lesson 3/Grandfather.m4a" },
        { mongolian: "Эмээ", pronunciation: "Emee", english: "Grandmother", audio: "audio/Mots/lesson 3/Grandmother.m4a" },
        { mongolian: "Нөхөр", pronunciation: "Nökhör", english: "Husband", audio: "audio/Mots/lesson 3/Husband.m4a" },
        { mongolian: "Эхнэр", pronunciation: "Ekhner", english: "Wife", audio: "audio/Mots/lesson 3/Wife.m4a" },
        { mongolian: "Гэр бүл", pronunciation: "Ger bül", english: "Family", audio: "audio/Mots/lesson 3/Family.m4a" },
        { mongolian: "Хүү", pronunciation: "Khüü", english: "Son", audio: "audio/Mots/lesson 3/Son.m4a" },
        { mongolian: "Охин", pronunciation: "Okhin", english: "Daughter", audio: "audio/Mots/lesson 3/Daughter.m4a" },
        { mongolian: "Хадам", pronunciation: "Khadam", english: "In-law", audio: "audio/Mots/lesson 3/in_law.m4a" },
        { mongolian: "Хамаатан", pronunciation: "Khamaatan", english: "Relative", audio: "audio/Mots/lesson 3/Relative.m4a" },
        { mongolian: "Найз", pronunciation: "Naiz", english: "Friend", audio: "audio/Mots/lesson 3/Friend.m4a" },
        { mongolian: "Ах дүү ", pronunciation: "Akh düü", english: "Siblings", audio: "audio/Mots/lesson 3/Siblings.m4a" },
        { mongolian: "Хүүгийн", pronunciation: "Khüügiin", english: "Male child's", audio: "audio/Mots/lesson 3/male_childs.m4a" },
        { mongolian: "Охины", pronunciation: "Okhiny", english: "Female child's", audio: "audio/Mots/lesson 3/female_childs.m4a" },
        { mongolian: "Гэрлэлт", pronunciation: "Gerleet", english: "Mariage", audio: "audio/Mots/lesson 3/Mariage.m4a" },
    ],
    food: [
        { mongolian: "Хоол", pronunciation: "Khol", english: "Food", audio: "audio/Mots/lesson4/Food.mp3" },
        { mongolian: "Ус", pronunciation: "Us", english: "Water", audio: "audio/Mots/lesson4/Water.mp3" },
        { mongolian: "Сүү", pronunciation: "Süü", english: "Milk", audio: "audio/Mots/lesson4/Milk.mp3" },
        { mongolian: "Цай", pronunciation: "Tsai", english: "Tea", audio: "audio/Mots/lesson4/Tea.mp3" },
        { mongolian: "Кофе", pronunciation: "Kofe", english: "Coffee", audio: "audio/Mots/lesson4/Coffee.mp3" },
        { mongolian: "Талх", pronunciation: "Talkh", english: "Bread", audio: "audio/Mots/lesson4/Bread.mp3" },
        { mongolian: "Будаа", pronunciation: "Budaa", english: "Rice", audio: "audio/Mots/lesson4/Rice.mp3" },
        { mongolian: "Гоймон", pronunciation: "Goimon", english: "Noodles", audio: "audio/Mots/lesson4/Noodles.mp3" },
        { mongolian: "Мах", pronunciation: "Makh", english: "Meat", audio: "audio/Mots/lesson4/Meat.mp3" },
        { mongolian: "Хонины мах", pronunciation: "Khoniny makh", english: "Mutton", audio: "audio/Mots/lesson4/Mutton.mp3" },
        { mongolian: "Үхрийн мах", pronunciation: "Ükhriin makh", english: "Beef", audio: "audio/Mots/lesson4/Beef.mp3" },
        { mongolian: "Тахианы мах", pronunciation: "Takhiiny makh", english: "Chicken", audio: "audio/Mots/lesson4/Chicken.mp3" },
        { mongolian: "Загас", pronunciation: "Zagas", english: "Fish", audio: "audio/Mots/lesson4/Fish.mp3" },
        { mongolian: "Жимс", pronunciation: "Jims", english: "Fruit", audio: "audio/Mots/lesson4/Fruit.mp3" },
        { mongolian: "Ногоо", pronunciation: "Nogoo", english: "Vegetables", audio: "audio/Mots/lesson4/Vegetables.mp3" },
        { mongolian: "Чихэр", pronunciation: "Chikher", english: "Candy", audio: "audio/Mots/lesson4/Candy.mp3" },
        { mongolian: "Жигнэмэг", pronunciation: "Jignemeg", english: "Biscuit", audio: "audio/Mots/lesson4/Biscuit.mp3" },
        { mongolian: "Өндөг", pronunciation: "Öndög", english: "Egg", audio: "audio/Mots/lesson4/Egg.mp3" },
        { mongolian: "Шөл", pronunciation: "Shöl", english: "Soup", audio: "audio/Mots/lesson4/Soup.mp3" },
        { mongolian: "Халуун", pronunciation: "Khaluun", english: "Hot", audio: "audio/Mots/lesson4/Hot.mp3" }
    ],
    colors: [
        { mongolian: "Улаан", pronunciation: "Ulaan", english: "Red", audio: "audio/Mots/lesson5/Red.mp3" },
        { mongolian: "Цэнхэр", pronunciation: "Tsenkher", english: "Blue", audio: "audio/Mots/lesson5/Blue.mp3" },
        { mongolian: "Ногоон", pronunciation: "Nogoon", english: "Green", audio: "audio/Mots/lesson5/Green.mp3" },
        { mongolian: "Шар", pronunciation: "Shar", english: "Yellow", audio: "audio/Mots/lesson5/Yellow.mp3" },
        { mongolian: "Хар", pronunciation: "Khar", english: "Black", audio: "audio/Mots/lesson5/Black.mp3" },
        { mongolian: "Цагаан", pronunciation: "Tsagaan", english: "White", audio: "audio/Mots/lesson5/White.mp3" },
        { mongolian: "Хүрэн", pronunciation: "Khüren", english: "Brown", audio: "audio/Mots/lesson5/Brown.mp3" },
        { mongolian: "Саарал", pronunciation: "Saaral", english: "Gray", audio: "audio/Mots/lesson5/Gray.mp3" },
        { mongolian: "Ягаан", pronunciation: "Yagaan", english: "Pink", audio: "audio/Mots/lesson5/Pink.mp3" },
        { mongolian: "Нил ягаан", pronunciation: "Nil yagaan", english: "Purple", audio: "audio/Mots/lesson5/Purple.mp3" },
        { mongolian: "Улбар шар", pronunciation: "Ulbar shar", english: "Orange", audio: "audio/Mots/lesson5/Orange.mp3" },
        { mongolian: "Цайвар", pronunciation: "Tsaiwar", english: "Light", audio: "audio/Mots/lesson5/light.mp3" },
        { mongolian: "Бараан", pronunciation: "Baraan", english: "Dark", audio: "audio/Mots/lesson5/Dark.mp3" },
        { mongolian: "Тод", pronunciation: "Tod", english: "Bright", audio: "audio/Mots/lesson5/Bright.mp3" },
        { mongolian: "Бүдгэрсэн", pronunciation: "Büdgersen", english: "Faded", audio: "audio/Mots/lesson5/faded.mp3" },
        { mongolian: "Хурц", pronunciation: "Khurts", english: "Vivid", audio: "audio/Mots/lesson5/vivid.mp3" },
        { mongolian: "Сүүдэртэй", pronunciation: "Süüdertei", english: "Shadowed", audio: "audio/Mots/lesson5/shadowed.mp3" },
        { mongolian: "Гэгээлэг", pronunciation: "Gegeelekh", english: "Sunny", audio: "audio/Mots/lesson5/sunny.mp3" },
        { mongolian: "Ясархаг", pronunciation: "Yasarkhag", english: "Pale", audio: "audio/Mots/lesson5/pale.mp3" },
        { mongolian: "Үлгэрийн", pronunciation: "Ülgeriin", english: "Pastel", audio: "audio/Mots/lesson5/pastel.mp3" }
    ],
    nature: [
        { mongolian: "Тэнгэр", pronunciation: "Tenger", english: "Sky", audio: "audio/Mots/lesson6/Тэнгэр.mp3" },
        { mongolian: "Нар", pronunciation: "Nar", english: "Sun", audio: "audio/Mots/lesson6/Нар.mp3" },
        { mongolian: "Сар", pronunciation: "Sar", english: "Moon", audio: "audio/Mots/lesson6/Сар.mp3" },
        { mongolian: "Од", pronunciation: "Od", english: "Star", audio: "audio/Mots/lesson6/Од.mp3" },
        { mongolian: "Ус", pronunciation: "Us", english: "Water", audio: "audio/Mots/lesson6/Ус.mp3" },
        { mongolian: "Цас", pronunciation: "Tsas", english: "Snow", audio: "audio/Mots/lesson6/Цас.mp3" },
        { mongolian: "Бороо", pronunciation: "Boroo", english: "Rain", audio: "audio/Mots/lesson6/Бороо.mp3" },
        { mongolian: "Салхи", pronunciation: "Salkhi", english: "Wind", audio: "audio/Mots/lesson6/Салхи.mp3" },
        { mongolian: "Гол", pronunciation: "Gol", english: "River", audio: "audio/Mots/lesson6/Гол.mp3" },
        { mongolian: "Нуур", pronunciation: "Nuur", english: "Lake", audio: "audio/Mots/lesson6/Нуур.mp3" },
        { mongolian: "Уул", pronunciation: "Uul", english: "Mountain", audio: "audio/Mots/lesson6/Уул.mp3" },
        { mongolian: "Тал", pronunciation: "Tal", english: "Plain", audio: "audio/Mots/lesson6/Тал.mp3" },
        { mongolian: "Ой", pronunciation: "Oi", english: "Forest", audio: "audio/Mots/lesson6/Оn.mp3" },
        { mongolian: "Элс", pronunciation: "Els", english: "Sand", audio: "audio/Mots/lesson6/Элс.mp3" },
        { mongolian: "Хад", pronunciation: "Khad", english: "Rock", audio: "audio/Mots/lesson6/Хад.mp3" },
        { mongolian: "Цэцэг", pronunciation: "Tsetseg", english: "Flower", audio: "audio/Mots/lesson6/Цэцэг.mp3" },
        { mongolian: "Мод", pronunciation: "Mod", english: "Tree", audio: "audio/Mots/lesson6/Мод.mp3" },
        { mongolian: "Навч", pronunciation: "Navch", english: "Leaf", audio: "audio/Mots/lesson6/Навч.mp3" },
        { mongolian: "Хөрс", pronunciation: "Khörs", english: "Soil", audio: "audio/Mots/lesson6/Хөрс.mp3" },
        { mongolian: "Амьтан", pronunciation: "Am'tan", english: "Animal", audio: "audio/Mots/lesson6/Амьтан.mp3" }
    ],


    transport: [
        { mongolian: "Машин", pronunciation: "Mashin", english: "Car", audio: "audio/Mots/lesson7/Машин.mp3" },
        { mongolian: "Унадаг дугуй", pronunciation: "Unadag dugui", english: "Bicycle", audio: "audio/Mots/lesson7/bicycle.mp3" },
        { mongolian: "Автобус", pronunciation: "Avtobus", english: "Bus", audio: "audio/Mots/lesson7/Автобус.mp3" },
        { mongolian: "Галт тэрэг", pronunciation: "Galt tereg", english: "Train", audio: "audio/Mots/lesson7/Галт тэрэг.mp3" },
        { mongolian: "Нисэх онгоц", pronunciation: "Nisekh ongots", english: "Airplane", audio: "audio/Mots/lesson7/Нисэх онгоц.mp3" },
        { mongolian: "Завь", pronunciation: "Zav", english: "Boat", audio: "audio/Mots/lesson7/Завь.mp3" },
        { mongolian: "Такси", pronunciation: "Taksi", english: "Taxi", audio: "audio/Mots/lesson7/Такси.mp3" },
        { mongolian: "Метро", pronunciation: "Metro", english: "Metro", audio: "audio/Mots/lesson7/Метро.mp3" },
        { mongolian: "Мотоцикл", pronunciation: "Motsikl", english: "Motorcycle", audio: "audio/Mots/lesson7/Мотоцикл.mp3" },
        { mongolian: "Зам", pronunciation: "Zam", english: "Road", audio: "audio/Mots/lesson7/Зам.mp3" },
        { mongolian: "Тасалбар", pronunciation: "Tasalkhar", english: "Ticket", audio: "audio/Mots/lesson7/Тасалбар.mp3" },
        { mongolian: "Зогсоол", pronunciation: "Zogsool", english: "Stop", audio: "audio/Mots/lesson7/Зогсоол.mp3" },
        { mongolian: "Жолооч", pronunciation: "Jolooch", english: "Driver", audio: "audio/Mots/lesson7/Жолооч.mp3" },
        { mongolian: "Суудал", pronunciation: "Soodal", english: "Seat", audio: "audio/Mots/lesson7/Суудал.mp3" },
        { mongolian: "Гарах", pronunciation: "Garkh", english: "Exit", audio: "audio/Mots/lesson7/Гарах.mp3" },
        { mongolian: "Орох", pronunciation: "Orokh", english: "Entrance", audio: "audio/Mots/lesson7/Орох.mp3" },
        { mongolian: "Бараан ачаа", pronunciation: "Baraan achaa", english: "Luggage", audio: "audio/Mots/lesson7/Бараан ачаа.mp3" },
        { mongolian: "Аюулгүй", pronunciation: "Ayulgüi", english: "Safe", audio: "audio/Mots/lesson7/Аюулгүй.mp3" },
        { mongolian: "Түргэн", pronunciation: "Türgen", english: "Fast", audio: "audio/Mots/lesson7/Түргэн.mp3" },
        { mongolian: "Удаан", pronunciation: "Udaan", english: "Slow", audio: "audio/Mots/lesson7/Удаан.mp3" }
    ],
    shopping: [
        { mongolian: "Дэлгүүр", pronunciation: "Delgüür", english: "Shop", audio: "audio/Mots/lesson8/Дэлгүүр.mp3" },
        { mongolian: "Үнэтэй", pronunciation: "Üntei", english: "Expensive", audio: "audio/Mots/lesson8/Үнэтэn.mp3" },
        { mongolian: "Хямд", pronunciation: "Khyamd", english: "Cheap", audio: "audio/Mots/lesson8/Хямд.mp3" },
        { mongolian: "Мөнгө", pronunciation: "Möngö", english: "Money", audio: "audio/Mots/lesson8/Мөнгө.mp3" },
        { mongolian: "Төлбөр", pronunciation: "Tölbör", english: "Payment", audio: "audio/Mots/lesson8/Төлбөр.mp3" },
        { mongolian: "Бэлэн мөнгө", pronunciation: "Belen möngö", english: "Cash", audio: "audio/Mots/lesson8/Бэлэн мөнгө.mp3" },
        { mongolian: "Карт", pronunciation: "Kart", english: "Card", audio: "audio/Mots/lesson8/Карт.mp3" },
        { mongolian: "Бараа", pronunciation: "Baraa", english: "Goods", audio: "audio/Mots/lesson8/Бараа.mp3" },
        { mongolian: "Хэрэгтэй", pronunciation: "Kheregtei", english: "Necessary", audio: "audio/Mots/lesson8/Хэрэгтэй.mp3" },
        { mongolian: "Хэрэггүй", pronunciation: "Khereggüi", english: "Not necessary", audio: "audio/Mots/lesson8/Хэрэггүn.mp3" },
        { mongolian: "Дүн", pronunciation: "Dün", english: "Total", audio: "audio/Mots/lesson8/Дүн.mp3" },
        { mongolian: "Хямдрал", pronunciation: "Khyamral", english: "Sale", audio: "audio/Mots/lesson8/Хямдрал.mp3" },
        { mongolian: "Тунгалаг", pronunciation: "Tungalag", english: "Transparent", audio: "audio/Mots/lesson8/Тунгалаг.mp3" },
        { mongolian: "Нэр", pronunciation: "Ner", english: "Brand", audio: "audio/Mots/lesson8/Нэр.mp3" },
        { mongolian: "Захиалга", pronunciation: "Zakhiagaa", english: "Order", audio: "audio/Mots/lesson8/Захиалга.mp3" },
        { mongolian: "Хүргэлт", pronunciation: "Khürgelt", english: "Delivery", audio: "audio/Mots/lesson8/Хүргэлт.mp3" },
        { mongolian: "Сав баглаа", pronunciation: "Sav baglaa", english: "Packaging", audio: "audio/Mots/lesson8/Сав баглаа.mp3" },
        { mongolian: "Шинэ", pronunciation: "Shine", english: "New", audio: "audio/Mots/lesson8/Шинэ.mp3" },
        { mongolian: "Хуучин", pronunciation: "Khuuchin", english: "Old", audio: "audio/Mots/lesson8/Хуучин.mp3" },
        { mongolian: "Бүтээгдэхүүн", pronunciation: "Bütedekhüün", english: "Product", audio: "audio/Mots/lesson8/Бүтээгдэхүүн.mp3" }
    ],
    weather: [
        { mongolian: "Дулаан", pronunciation: "Dulaan", english: "Warm", audio: "audio/Mots/lesson9/warm.mp3" },
        { mongolian: "Хүйтэн", pronunciation: "Khüiten", english: "Cold", audio: "audio/Mots/lesson9/cold.mp3" },
        { mongolian: "Халуун", pronunciation: "Khaluun", english: "Hot", audio: "audio/Mots/lesson9/hot.mp3" },
        { mongolian: "Сэрүүн", pronunciation: "Serüün", english: "Cool", audio: "audio/Mots/lesson9/cool.mp3" },
        { mongolian: "Салхи", pronunciation: "Salkhi", english: "Windy", audio: "audio/Mots/lesson9/windy.mp3" },
        { mongolian: "Бороотой", pronunciation: "Borootoi", english: "Rainy", audio: "audio/Mots/lesson9/rainy.mp3" },
        { mongolian: "Цастай", pronunciation: "Tsastai", english: "Snowy", audio: "audio/Mots/lesson9/snowy.mp3" },
        { mongolian: "Нарлаг", pronunciation: "Narlag", english: "Sunny", audio: "audio/Mots/lesson9/sunny.mp3" },
        { mongolian: "Үүлтэй", pronunciation: "Üültei", english: "Cloudy", audio: "audio/Mots/lesson9/cloudy.mp3" },
        { mongolian: "Багавтар", pronunciation: "Bagavtar", english: "Mild", audio: "audio/Mots/lesson9/mild.mp3" },
        { mongolian: "Аадар", pronunciation: "Aadar", english: "Storm", audio: "audio/Mots/lesson9/storm.mp3" },
        { mongolian: "Шороон шуурга", pronunciation: "Shoroon shuurg", english: "Sandstorm", audio: "audio/Mots/lesson9/sandstorm.mp3" },
        { mongolian: "Даралт", pronunciation: "Dral'lt", english: "Pressure", audio: "audio/Mots/lesson9/pressure.mp3" },
        { mongolian: "Чийгтэй", pronunciation: "Chiigtei", english: "Humid", audio: "audio/Mots/lesson9/humid.mp3" },
        { mongolian: "Чийггүй", pronunciation: "Chiiggüi", english: "Dry", audio: "audio/Mots/lesson9/dry.mp3" },
        { mongolian: "Сүүдэр", pronunciation: "Süder", english: "Shade", audio: "audio/Mots/lesson9/shade.mp3" },
        { mongolian: "Хүчтэй", pronunciation: "Khüchtei", english: "Strong", audio: "audio/Mots/lesson9/strong.mp3" },
        { mongolian: "Хөнгөн", pronunciation: "Khöngön", english: "Light", audio: "audio/Mots/lesson9/light.mp3" },
        { mongolian: "Өдөр", pronunciation: "Ödör", english: "Daytime", audio: "audio/Mots/lesson9/daytime.mp3" },
        { mongolian: "Шөнө", pronunciation: "Shönö", english: "Nighttime", audio: "audio/Mots/lesson9/nighttime.mp3" }
    ],
    activities: [
        { mongolian: "Босох", pronunciation: "Bosokh", english: "Wake up", audio: "audio/Mots/lesson10/wakeup.mp3" },
        { mongolian: "Унтах", pronunciation: "Untakh", english: "Sleep", audio: "audio/Mots/lesson10/sleep.mp3" },
        { mongolian: "Идэх", pronunciation: "Idekh", english: "Eat", audio: "audio/Mots/lesson10/eat.mp3" },
        { mongolian: "Уух", pronunciation: "Uukh", english: "Drink", audio: "audio/Mots/lesson10/drink.mp3" },
        { mongolian: "Ажлын", pronunciation: "Ajlin", english: "Work", audio: "audio/Mots/lesson10/work.mp3" },
        { mongolian: "Хичээл", pronunciation: "Khiichil", english: "Study", audio: "audio/Mots/lesson10/study.mp3" },
        { mongolian: "Тоглох", pronunciation: "Toglokh", english: "Play", audio: "audio/Mots/lesson10/play.mp3" },
        { mongolian: "Явах", pronunciation: "Yavakh", english: "Go", audio: "audio/Mots/lesson10/go.mp3" },
        { mongolian: "Ирэх", pronunciation: "Irekh", english: "Come", audio: "audio/Mots/lesson10/come.mp3" },
        { mongolian: "Үзэх", pronunciation: "Üzekh", english: "See", audio: "audio/Mots/lesson10/see.mp3" },
        { mongolian: "Сонсох", pronunciation: "Sonsoh", english: "Hear", audio: "audio/Mots/lesson10/hear.mp3" },
        { mongolian: "Бичих", pronunciation: "Bichikh", english: "Write", audio: "audio/Mots/lesson10/write.mp3" },
        { mongolian: "Унших", pronunciation: "Unshikh", english: "Read", audio: "audio/Mots/lesson10/read.mp3" },
        { mongolian: "Харах", pronunciation: "Kharakh", english: "Watch", audio: "audio/Mots/lesson10/watch.mp3" },
        { mongolian: "Зураг", pronunciation: "Zurag", english: "Draw", audio: "audio/Mots/lesson10/draw.mp3" },
        { mongolian: "Угаах", pronunciation: "Ugaakh", english: "Wash", audio: "audio/Mots/lesson10/wash.mp3" },
        { mongolian: "Хийх", pronunciation: "Khiikh", english: "Do", audio: "audio/Mots/lesson10/do.mp3" },
        { mongolian: "Амрах", pronunciation: "Amrakh", english: "Rest", audio: "audio/Mots/lesson10/rest.mp3" },
        { mongolian: "Хувцаслах", pronunciation: "Khuvtsaslah", english: "Get dressed", audio: "audio/Mots/lesson10/getdressed.mp3" },
        { mongolian: "Яриа", pronunciation: "Yaria", english: "Speak", audio: "audio/Mots/lesson10/speak.mp3" }
    ],
    body: [
        { mongolian: "Толгой", pronunciation: "tolgoi", english: "Head", audio: "audio/Mots/lesson11/head.mp3" },
        { mongolian: "Нүд", pronunciation: "nüd", english: "Eye", audio: "audio/Mots/lesson11/eye.mp3" },
        { mongolian: "Чих", pronunciation: "chikh", english: "Ear", audio: "audio/Mots/lesson11/ear.mp3" },
        { mongolian: "Хамар", pronunciation: "khamar", english: "Nose", audio: "audio/Mots/lesson11/nose.mp3" },
        { mongolian: "Ам", pronunciation: "am", english: "Mouth", audio: "audio/Mots/lesson11/mouth.mp3" },
        { mongolian: "Шүд", pronunciation: "shüd", english: "Tooth", audio: "audio/Mots/lesson11/tooth.mp3" },
        { mongolian: "Хүзүү", pronunciation: "khüzüü", english: "Neck", audio: "audio/Mots/lesson11/neck.mp3" },
        { mongolian: "Гар", pronunciation: "gar", english: "Hand", audio: "audio/Mots/lesson11/hand.mp3" },
        { mongolian: "Хөл", pronunciation: "khöl", english: "Leg", audio: "audio/Mots/lesson11/leg.mp3" },
        { mongolian: "Хуруу", pronunciation: "khuruu", english: "Finger", audio: "audio/Mots/lesson11/finger.mp3" },
        { mongolian: "Өвдөг", pronunciation: "övdög", english: "Knee", audio: "audio/Mots/lesson11/knee.mp3" },
        { mongolian: "Цээж", pronunciation: "tseej", english: "Chest", audio: "audio/Mots/lesson11/chest.mp3" },
        { mongolian: "Нуруу", pronunciation: "nuruu", english: "Back", audio: "audio/Mots/lesson11/back.mp3" },
        { mongolian: "Хурууны хумс", pronunciation: "khuruuny khums", english: "Fingernail", audio: "audio/Mots/lesson11/fingernail.mp3" },
        { mongolian: "Арьс", pronunciation: "arys", english: "Skin", audio: "audio/Mots/lesson11/skin.mp3" },
        { mongolian: "Үс", pronunciation: "üs", english: "Hair", audio: "audio/Mots/lesson11/hair.mp3" },
        { mongolian: "Зүрх", pronunciation: "zürkh", english: "Heart", audio: "audio/Mots/lesson11/heart.mp3" },
        { mongolian: "Ходоод", pronunciation: "khodood", english: "Stomach", audio: "audio/Mots/lesson11/stomach.mp3" },
        { mongolian: "Мөч", pronunciation: "möch", english: "Limb", audio: "audio/Mots/lesson11/limb.mp3" },
        { mongolian: "Нүүр", pronunciation: "nüür", english: "Face", audio: "audio/Mots/lesson11/face.mp3" }
    ],
    emotions: [
        { mongolian: "Аз жаргал", pronunciation: "az jargal", english: "Happiness", audio: "audio/Mots/lesson12/happiness.mp3" },
        { mongolian: "Уур", pronunciation: "uur", english: "Anger", audio: "audio/Mots/lesson12/anger.mp3" },
        { mongolian: "Гуниг", pronunciation: "gunig", english: "Sadness", audio: "audio/Mots/lesson12/sadness.mp3" },
        { mongolian: "Айдас", pronunciation: "aidas", english: "Fear", audio: "audio/Mots/lesson12/fear.mp3" },
        { mongolian: "Сэтгэл хөдлөл", pronunciation: "setgel khödlel", english: "Emotion", audio: "audio/Mots/lesson12/emotion.mp3" },
        { mongolian: "Итгэл", pronunciation: "itgel", english: "Trust", audio: "audio/Mots/lesson12/trust.mp3" },
        { mongolian: "Эелдэг", pronunciation: "eeldeg", english: "Kindness", audio: "audio/Mots/lesson12/kindness.mp3" },
        { mongolian: "Шунал", pronunciation: "shunal", english: "Greed", audio: "audio/Mots/lesson12/greed.mp3" },
        { mongolian: "Өшөө авалт", pronunciation: "öshöö avalt", english: "Revenge", audio: "audio/Mots/lesson12/revenge.mp3" },
        { mongolian: "Талархал", pronunciation: "talarhal", english: "Gratitude", audio: "audio/Mots/lesson12/gratitude.mp3" },
        { mongolian: "Бахархал", pronunciation: "bakharkhal", english: "Pride", audio: "audio/Mots/lesson12/pride.mp3" },
        { mongolian: "Шок", pronunciation: "shok", english: "Shock", audio: "audio/Mots/lesson12/shock.mp3" },
        { mongolian: "Хайр", pronunciation: "khair", english: "Love", audio: "audio/Mots/lesson12/love.mp3" },
        { mongolian: "Харамсал", pronunciation: "kharamsal", english: "Regret", audio: "audio/Mots/lesson12/regret.mp3" },
        { mongolian: "Инээд", pronunciation: "ineed", english: "Laughter", audio: "audio/Mots/lesson12/laughter.mp3" },
        { mongolian: "Урам хугарах", pronunciation: "uram khugarakh", english: "Disappointment", audio: "audio/Mots/lesson12/disappointment.mp3" },
        { mongolian: "Эвгүйцэх", pronunciation: "evgüitsekh", english: "Embarrassment", audio: "audio/Mots/lesson12/embarrassment.mp3" },
        { mongolian: "Баяр", pronunciation: "bayar", english: "Joy", audio: "audio/Mots/lesson12/joy.mp3" },
        { mongolian: "Гайхширал", pronunciation: "gaikhshiral", english: "Surprise", audio: "audio/Mots/lesson12/surprise.mp3" },
        { mongolian: "Тайван", pronunciation: "taivan", english: "Calm", audio: "audio/Mots/lesson12/calm.mp3" }
    ],
    occupations: [
        { mongolian: "Эмч", pronunciation: "emch", english: "Doctor", audio: "audio/Mots/lesson13/doctor.mp3" },
        { mongolian: "Сувилагч", pronunciation: "suvilagch", english: "Nurse", audio: "audio/Mots/lesson13/nurse.mp3" },
        { mongolian: "Багш", pronunciation: "bagsh", english: "Teacher", audio: "audio/Mots/lesson13/teacher.mp3" },
        { mongolian: "Оюутан", pronunciation: "oyutan", english: "Student", audio: "audio/Mots/lesson13/student.mp3" },
        { mongolian: "Жолооч", pronunciation: "jolooch", english: "Driver", audio: "audio/Mots/lesson13/driver.mp3" },
        { mongolian: "Худалдагч", pronunciation: "khudaldagch", english: "Seller", audio: "audio/Mots/lesson13/seller.mp3" },
        { mongolian: "Цагдаа", pronunciation: "tsagdaa", english: "Police officer", audio: "audio/Mots/lesson13/policeofficer.mp3" },
        { mongolian: "Гал сөнөөгч", pronunciation: "gal söngööch", english: "Firefighter", audio: "audio/Mots/lesson13/firefighter.mp3" },
        { mongolian: "Инженер", pronunciation: "injener", english: "Engineer", audio: "audio/Mots/lesson13/engineer.mp3" },
        { mongolian: "Хуульч", pronunciation: "khuulich", english: "Lawyer", audio: "audio/Mots/lesson13/lawyer.mp3" },
        { mongolian: "Фермер", pronunciation: "fermer", english: "Farmer", audio: "audio/Mots/lesson13/farmer.mp3" },
        { mongolian: "Зураач", pronunciation: "zuraach", english: "Artist", audio: "audio/Mots/lesson13/artist.mp3" },
        { mongolian: "Жүжигчин", pronunciation: "jüjigchin", english: "Actor", audio: "audio/Mots/lesson13/actor.mp3" },
        { mongolian: "Даяанч", pronunciation: "dayanch", english: "Monk", audio: "audio/Mots/lesson13/monk.mp3" },
        { mongolian: "Нягтлан бодогч", pronunciation: "nyagtlan bodogch", english: "Accountant", audio: "audio/Mots/lesson13/accountant.mp3" },
        { mongolian: "Згвар зохион бүтээгч", pronunciation: "zagvar zohion büüteegch", english: "Designer", audio: "audio/Mots/lesson13/designer.mp3" },
        { mongolian: "Программист", pronunciation: "programmist", english: "Programmer", audio: "audio/Mots/lesson13/programmer.mp3" },
        { mongolian: "Орчуулагч", pronunciation: "orchuulagch", english: "Translator", audio: "audio/Mots/lesson13/translator.mp3" },
        { mongolian: "Журналист", pronunciation: "jurnalist", english: "Journalist", audio: "audio/Mots/lesson13/journalist.mp3" },
        { mongolian: "Удирдагч", pronunciation: "udirdagch", english: "Leader", audio: "audio/Mots/lesson13/leader.mp3" }
    ],
    clothing: [
        { mongolian: "Гутал", pronunciation: "gutal", english: "Shoes", audio: "audio/Mots/lesson14/shoes.mp3" },
        { mongolian: "Цамц", pronunciation: "tsamts", english: "Shirt", audio: "audio/Mots/lesson14/shirt.mp3" },
        { mongolian: "Өмд", pronunciation: "ömd", english: "Pants", audio: "audio/Mots/lesson14/pants.mp3" },
        { mongolian: "Юбка", pronunciation: "yubka", english: "Skirt", audio: "audio/Mots/lesson14/skirt.mp3" },
        { mongolian: "Даашинз", pronunciation: "daashinz", english: "Dress", audio: "audio/Mots/lesson14/dress.mp3" },
        { mongolian: "Малгай", pronunciation: "malgai", english: "Hat", audio: "audio/Mots/lesson14/hat.mp3" },
        { mongolian: "роолт", pronunciation: "oroolt", english: "Scarf", audio: "audio/Mots/lesson14/scarf.mp3" },
        { mongolian: "Бээлий", pronunciation: "beelii", english: "Gloves", audio: "audio/Mots/lesson14/gloves.mp3" },
        { mongolian: "Куртка", pronunciation: "kurtka", english: "Jacket", audio: "audio/Mots/lesson14/jacket.mp3" },
        { mongolian: "Цув", pronunciation: "tsuv", english: "Coat", audio: "audio/Mots/lesson14/coat.mp3" },
        { mongolian: "Туфль", pronunciation: "tufl", english: "Heels", audio: "audio/Mots/lesson14/heels.mp3" },
        { mongolian: "Дотуур хувцас", pronunciation: "dotuur khuvtsas", english: "Underwear", audio: "audio/Mots/lesson14/underwear.mp3" },
        { mongolian: "Бүс", pronunciation: "büs", english: "Belt", audio: "audio/Mots/lesson14/belt.mp3" },
        { mongolian: "Оймс", pronunciation: "oyms", english: "Socks", audio: "audio/Mots/lesson14/socks.mp3" },
        { mongolian: "Цүнх", pronunciation: "tsünkh", english: "Bag", audio: "audio/Mots/lesson14/bag.mp3" },
        { mongolian: "Нүдний шил", pronunciation: "nüdnij shil", english: "Glasses", audio: "audio/Mots/lesson14/glasses.mp3" },
        { mongolian: "Зүүлт", pronunciation: "züült", english: "Necklace", audio: "audio/Mots/lesson14/necklace.mp3" },
        { mongolian: "Бугуйвч", pronunciation: "buguivch", english: "Bracelet", audio: "audio/Mots/lesson14/bracelet.mp3" },
        { mongolian: "Цаг", pronunciation: "tsag", english: "Watch", audio: "audio/Mots/lesson14/watch.mp3" },
        { mongolian: "Жижиг цүнх", pronunciation: "jijig tsünkh", english: "Purse", audio: "audio/Mots/lesson14/purse.mp3" }
    ],
    animals: [
        { mongolian: "Нохой", pronunciation: "nokhoi", english: "Dog", audio: "audio/Mots/lesson15/dog.mp3" },
        { mongolian: "Муур", pronunciation: "müür", english: "Cat", audio: "audio/Mots/lesson15/cat.mp3" },
        { mongolian: "Морь", pronunciation: "mor'", english: "Horse", audio: "audio/Mots/lesson15/horse.mp3" },
        { mongolian: "Үхэр", pronunciation: "ükher", english: "Cow", audio: "audio/Mots/lesson15/cow.mp3" },
        { mongolian: "Хонь", pronunciation: "khon'", english: "Sheep", audio: "audio/Mots/lesson15/sheep.mp3" },
        { mongolian: "Ямаа", pronunciation: "yamaa", english: "Goat", audio: "audio/Mots/lesson15/goat.mp3" },
        { mongolian: "Гүүхай", pronunciation: "gakhai", english: "Pig", audio: "audio/Mots/lesson15/pig.mp3" },
        { mongolian: "Тахиа", pronunciation: "takhiia", english: "Chicken", audio: "audio/Mots/lesson15/chicken.mp3" },
        { mongolian: "Нугас", pronunciation: "nugas", english: "Duck", audio: "audio/Mots/lesson15/duck.mp3" },
        { mongolian: "Загас", pronunciation: "zagas", english: "Fish", audio: "audio/Mots/lesson15/fish.mp3" },
        { mongolian: "Чоно", pronunciation: "chono", english: "Wolf", audio: "audio/Mots/lesson15/wolf.mp3" },
        { mongolian: "Тэмээ", pronunciation: "temee", english: "Camel", audio: "audio/Mots/lesson15/camel.mp3" },
        { mongolian: "Баавгай", pronunciation: "baavgai", english: "Bear", audio: "audio/Mots/lesson15/bear.mp3" },
        { mongolian: "Арслан", pronunciation: "arslan", english: "Lion", audio: "audio/Mots/lesson15/lion.mp3" },
        { mongolian: "Заан", pronunciation: "zaan", english: "Elephant", audio: "audio/Mots/lesson15/elephant.mp3" },
        { mongolian: "Матар", pronunciation: "matar", english: "Crocodile", audio: "audio/Mots/lesson15/crocodile.mp3" },
        { mongolian: "Туулай", pronunciation: "tuulai", english: "Rabbit", audio: "audio/Mots/lesson15/rabbit.mp3" },
        { mongolian: "Хулгана", pronunciation: "khulgana", english: "Mouse", audio: "audio/Mots/lesson15/mouse.mp3" },
        { mongolian: "Шувуу", pronunciation: "shuvuu", english: "Bird", audio: "audio/Mots/lesson15/bird.mp3" },
        { mongolian: "Бурхнаас эрсэн загас", pronunciation: "burkhnaas ersen zagas", english: "Goldfish", audio: "audio/Mots/lesson15/goldfish.mp3" }
    ],
    technology: [
        { mongolian: "Гар утас", pronunciation: "gar utas", english: "Mobile phone", audio: "audio/Mots/lesson16/mobilephone.mp3" },
        { mongolian: "Компьютер", pronunciation: "kompyuter", english: "Computer", audio: "audio/Mots/lesson16/computer.mp3" },
        { mongolian: "Дэлгэц", pronunciation: "delgets", english: "Screen", audio: "audio/Mots/lesson16/screen.mp3" },
        { mongolian: "Зурагт", pronunciation: "zuragt", english: "Television", audio: "audio/Mots/lesson16/television.mp3" },
        { mongolian: "Камер", pronunciation: "kamer", english: "Camera", audio: "audio/Mots/lesson16/camera.mp3" },
        { mongolian: "Чихэвч", pronunciation: "chikhevch", english: "Headphones", audio: "audio/Mots/lesson16/headphones.mp3" },
        { mongolian: "Микрофон", pronunciation: "mikrofon", english: "Microphone", audio: "audio/Mots/lesson16/microphone.mp3" },
        { mongolian: "Тоглоом", pronunciation: "togloom", english: "Game", audio: "audio/Mots/lesson16/game.mp3" },
        { mongolian: "Интернет", pronunciation: "internet", english: "Internet", audio: "audio/Mots/lesson16/internet.mp3" },
        { mongolian: "Зай", pronunciation: "zai", english: "Battery", audio: "audio/Mots/lesson16/battery.mp3" },
        { mongolian: "Гар хулгана", pronunciation: "gar khulgana", english: "Mouse (computer)", audio: "audio/Mots/lesson16/mouse.mp3" },
        { mongolian: "Принтер", pronunciation: "printer", english: "Printer", audio: "audio/Mots/lesson16/printer.mp3" },
        { mongolian: "Гэрэл зургийн аппарат", pronunciation: "gerel zuragiin apparat", english: "Photo camera", audio: "audio/Mots/lesson16/photocamera.mp3" },
        { mongolian: "Хард диск", pronunciation: "khard disk", english: "Hard drive", audio: "audio/Mots/lesson16/harddrive.mp3" },
        { mongolian: "Гар", pronunciation: "gar", english: "Keyboard", audio: "audio/Mots/lesson16/keyboard.mp3" },
        { mongolian: "Ухаалаг цаг", pronunciation: "ukhaalag tsag", english: "Smartwatch", audio: "audio/Mots/lesson16/smartwatch.mp3" },
        { mongolian: "Хэвлэгч", pronunciation: "khevlegch", english: "Scanner", audio: "audio/Mots/lesson16/scanner.mp3" },
        { mongolian: "Таблет", pronunciation: "tablet", english: "Tablet", audio: "audio/Mots/lesson16/tablet.mp3" },
        { mongolian: "Ухаалаг утас", pronunciation: "ukhaalag utas", english: "Smartphone", audio: "audio/Mots/lesson16/smartphone.mp3" },
        { mongolian: "Чип", pronunciation: "chip", english: "Chip", audio: "audio/Mots/lesson16/chip.mp3" }
    ],
    hobbies: [
        { mongolian: "Ном унших", pronunciation: "nom unshikh", english: "Reading", audio: "audio/Mots/lesson17/reading.mp3" },
        { mongolian: "Зураг зурах", pronunciation: "zurag zurakh", english: "Drawing", audio: "audio/Mots/lesson17/drawing.mp3" },
        { mongolian: "Бичих", pronunciation: "bichikh", english: "Writing", audio: "audio/Mots/lesson17/writing.mp3" },
        { mongolian: "Тоглох", pronunciation: "toglokh", english: "Playing", audio: "audio/Mots/lesson17/playing.mp3" },
        { mongolian: "Дуучлах", pronunciation: "duuchlakh", english: "Singing", audio: "audio/Mots/lesson17/singing.mp3" },
        { mongolian: "Бүжиглэх", pronunciation: "büjiglekh", english: "Dancing", audio: "audio/Mots/lesson17/dancing.mp3" },
        { mongolian: "Жүжиглэх", pronunciation: "jüjiglekh", english: "Acting", audio: "audio/Mots/lesson17/acting.mp3" },
        { mongolian: "Спорт тоглох", pronunciation: "sport toglogh", english: "Playing sports", audio: "audio/Mots/lesson17/playingsports.mp3" },
        { mongolian: "Дуулах", pronunciation: "duulakh", english: "Singing", audio: "audio/Mots/lesson17/singing.mp3" },
        { mongolian: "Дугуй унах", pronunciation: "dugui unakh", english: "Cycling", audio: "audio/Mots/lesson17/cycling.mp3" },
        { mongolian: "Кино үзэх", pronunciation: "kino üzekh", english: "Watching movies", audio: "audio/Mots/lesson17/watchingmovies.mp3" },
        { mongolian: "Загасчлах", pronunciation: "zagaschlakh", english: "Fishing", audio: "audio/Mots/lesson17/fishing.mp3" },
        { mongolian: "Нэхэх", pronunciation: "nekekh", english: "Knitting", audio: "audio/Mots/lesson17/knitting.mp3" },
        { mongolian: "Зайрмаг идэх", pronunciation: "zaimrag idekh", english: "Eating ice cream", audio: "audio/Mots/lesson17/icecream.mp3" },
        { mongolian: "Бялуу хийх", pronunciation: "byaluu khiikh", english: "Baking cakes", audio: "audio/Mots/lesson17/cakes.mp3" },
        { mongolian: "Зохион бичих", pronunciation: "zokhion bichikh", english: "Composing", audio: "audio/Mots/lesson17/composing.mp3" },
        { mongolian: "Хэл сурах", pronunciation: "khel surakh", english: "Learning languages", audio: "audio/Mots/lesson17/languages.mp3" },
        { mongolian: "Зураг авах", pronunciation: "zurag avakh", english: "Taking photos", audio: "audio/Mots/lesson17/photos.mp3" },
        { mongolian: "Дуран харах", pronunciation: "duran kharakh", english: "Stargazing", audio: "audio/Mots/lesson17/stargazing.mp3" },
        { mongolian: "Усан санд сэлэх", pronunciation: "usan sand selekh", english: "Swimming", audio: "audio/Mots/lesson17/swimming.mp3" }
    ],
    travel: [
        { mongolian: "Онгоц", pronunciation: "ongots", english: "Plane", audio: "audio/Mots/lesson18/plane.mp3" },
        { mongolian: "Галт тэрэг", pronunciation: "galt tereg", english: "Train", audio: "audio/Mots/lesson18/train.mp3" },
        { mongolian: "Хөлөг онгоц", pronunciation: "khölög ongots", english: "Ship", audio: "audio/Mots/lesson18/ship.mp3" },
        { mongolian: "Нисэх буудал", pronunciation: "niskh buudal", english: "Airport", audio: "audio/Mots/lesson18/airport.mp3" },
        { mongolian: "Зочид буудал", pronunciation: "zochid buudal", english: "Hotel", audio: "audio/Mots/lesson18/hotel.mp3" },
        { mongolian: "Гэр", pronunciation: "ger", english: "Ger (traditional tent)", audio: "audio/Mots/lesson18/ger.mp3" },
        { mongolian: "Хоолны газар", pronunciation: "khoolni gazar", english: "Restaurant", audio: "audio/Mots/lesson18/restaurant.mp3" },
        { mongolian: "Газрын зураг", pronunciation: "gazarin zurag", english: "Map", audio: "audio/Mots/lesson18/map.mp3" },
        { mongolian: "Аялал", pronunciation: "ayalal", english: "Travel", audio: "audio/Mots/lesson18/travel.mp3" },
        { mongolian: "Хил", pronunciation: "khil", english: "Border", audio: "audio/Mots/lesson18/bordel.mp3" },
        { mongolian: "Виз", pronunciation: "viz", english: "Visa", audio: "audio/Mots/lesson18/visa.mp3" },
        { mongolian: "Буудал", pronunciation: "buudal", english: "Stop", audio: "audio/Mots/lesson18/stop.mp3" },
        { mongolian: "Хөтөч", pronunciation: "khötöch", english: "Guide", audio: "audio/Mots/lesson18/guide.mp3" },
        { mongolian: "Жуулчин", pronunciation: "juulchin", english: "Tourist", audio: "audio/Mots/lesson18/tourist.mp3" },
        { mongolian: "Аялал жуулчлал", pronunciation: "ayalal juulchlal", english: "Tourism", audio: "audio/Mots/lesson18/tourism.mp3" },
        { mongolian: "Зам", pronunciation: "zam", english: "Road", audio: "audio/Mots/lesson18/road.mp3" },
        { mongolian: "Цүнх", pronunciation: "tsünkh", english: "Luggage", audio: "audio/Mots/lesson18/luggage.mp3" },
        { mongolian: "Газрын тос", pronunciation: "gazriin tos", english: "Petrol", audio: "audio/Mots/lesson18/petrol.mp3" },
        { mongolian: "Галт тэрэгний буудал", pronunciation: "galt teregnii buudal", english: "Train station", audio: "audio/Mots/lesson18/train station.mp3" },
        { mongolian: "Картаар төлөх", pronunciation: "kartaar tölökh", english: "Pay by card", audio: "audio/Mots/lesson18/paybycard.mp3" }
    ],
    shapes: [
        { mongolian: "Тойрог", pronunciation: "toirog", english: "Circle", audio: "audio/Mots/lesson19/circle.mp3" },
        { mongolian: "Дөрвөлжин", pronunciation: "dörvöljin", english: "Square", audio: "audio/Mots/lesson19/square.mp3" },
        { mongolian: "Гурвалжин", pronunciation: "gurwaljin", english: "Triangle", audio: "audio/Mots/lesson19/triangle.mp3" },
        { mongolian: "Урт", pronunciation: "urt", english: "Long", audio: "audio/Mots/lesson19/long.mp3" },
        { mongolian: "Богино", pronunciation: "bogino", english: "Short", audio: "audio/Mots/lesson19/short.mp3" },
        { mongolian: "Өргөн", pronunciation: "örgön", english: "Wide", audio: "audio/Mots/lesson19/wide.mp3" },
        { mongolian: "Нарийн", pronunciation: "nariin", english: "Narrow", audio: "audio/Mots/lesson19/narrow.mp3" },
        { mongolian: "Том", pronunciation: "tom", english: "Big", audio: "audio/Mots/lesson19/big.mp3" },
        { mongolian: "Жижиг", pronunciation: "jijig", english: "Small", audio: "audio/Mots/lesson19/small.mp3" },
        { mongolian: "Дундаж", pronunciation: "dundaj", english: "Average", audio: "audio/Mots/lesson19/average.mp3" },
        { mongolian: "Дугуй", pronunciation: "dugui", english: "Round", audio: "audio/Mots/lesson19/round.mp3" },
        { mongolian: "Хавтгай", pronunciation: "khawtgai", english: "Flat", audio: "audio/Mots/lesson19/flat.mp3" },
        { mongolian: "Гүдгэр", pronunciation: "güdger", english: "Convex", audio: "audio/Mots/lesson19/convex.mp3" },
        { mongolian: "Хөндлөн", pronunciation: "khöndlön", english: "Horizontal", audio: "audio/Mots/lesson19/horizontal.mp3" },
        { mongolian: "Босоо", pronunciation: "bosoo", english: "Vertical", audio: "audio/Mots/lesson19/vertical.mp3" },
        { mongolian: "Тэгш", pronunciation: "tegsh", english: "Equal", audio: "audio/Mots/lesson19/equal.mp3" },
        { mongolian: "Шулуун", pronunciation: "shuluun", english: "Straight", audio: "audio/Mots/lesson19/straight.mp3" },
        { mongolian: "Муруй", pronunciation: "murui", english: "Curved", audio: "audio/Mots/lesson19/curved.mp3" },
        { mongolian: "Өнцөг", pronunciation: "öntsög", english: "Angle", audio: "audio/Mots/lesson19/angle.mp3" },
        { mongolian: "Тэгш өнцөгт", pronunciation: "tegsh öntsögt", english: "Rectangle", audio: "audio/Mots/lesson19/rectangle.mp3" }
    ],
    verbs: [
        { mongolian: "Ярих", pronunciation: "yarikh", english: "To speak", audio: "audio/Mots/lesson20/speak.mp3" },
        { mongolian: "Сонсох", pronunciation: "sonsoh", english: "To listen", audio: "audio/Mots/lesson20/listen.mp3" },
        { mongolian: "Харах", pronunciation: "kharakh", english: "To look", audio: "audio/Mots/lesson20/look.mp3" },
        { mongolian: "Бичих", pronunciation: "bichikh", english: "To write", audio: "audio/Mots/lesson20/write.mp3" },
        { mongolian: "Унших", pronunciation: "unshikh", english: "To read", audio: "audio/Mots/lesson20/read.mp3" },
        { mongolian: "Босох", pronunciation: "bosokh", english: "To get up", audio: "audio/Mots/lesson20/getup.mp3" },
        { mongolian: "Сууцгаах", pronunciation: "suutsgaakh", english: "To sit", audio: "audio/Mots/lesson20/sit.mp3" },
        { mongolian: "Идэх", pronunciation: "idekh", english: "To eat", audio: "audio/Mots/lesson20/eat.mp3" },
        { mongolian: "Уух", pronunciation: "uukh", english: "To drink", audio: "audio/Mots/lesson20/drink.mp3" },
        { mongolian: "Инээх", pronunciation: "inee", english: "To smile", audio: "audio/Mots/lesson20/smile.mp3" },
        { mongolian: "Унтах", pronunciation: "untakh", english: "To sleep", audio: "audio/Mots/lesson20/sleep.mp3" },
        { mongolian: "Тоглох", pronunciation: "toglokh", english: "To play", audio: "audio/Mots/lesson20/play.mp3" },
        { mongolian: "Хийх", pronunciation: "khiikh", english: "To do", audio: "audio/Mots/lesson20/do.mp3" },
        { mongolian: "Туслах", pronunciation: "tuslakh", english: "To help", audio: "audio/Mots/lesson20/help.mp3" },
        { mongolian: "Хөөх", pronunciation: "khökh", english: "To chase", audio: "audio/Mots/lesson20/chase.mp3" },
        { mongolian: "Амрах", pronunciation: "amrakh", english: "To rest", audio: "audio/Mots/lesson20/rest.mp3" },
        { mongolian: "Сурах", pronunciation: "surakh", english: "To learn", audio: "audio/Mots/lesson20/learn.mp3" },
        { mongolian: "Заах", pronunciation: "zaakh", english: "To teach", audio: "audio/Mots/lesson20/teach.mp3" },
        { mongolian: "Авах", pronunciation: "avakh", english: "To take", audio: "audio/Mots/lesson20/take.mp3" },
        { mongolian: "Өгөх", pronunciation: "ögökh", english: "To give", audio: "audio/Mots/lesson20/give.mp3" }
    ]
}; 
