const vocabularyData = {
    greetings: [
        { mongolian: "Сайн уу", pronunciation: "Sain uu", english: "Hello", audio: "audio/Mots/lesson 1/hello.mp3" },
        { mongolian: "Сайн байна уу", pronunciation: "Sain baina uu", english: "How are you?", audio: "audio/Mots/lesson 1/how_are_you.mp3" },
        { mongolian: "Баярлалаа", pronunciation: "Bayarlalaa", english: "Thank you", audio: "audio/Mots/lesson 1/thank_you.mp3" },
        { mongolian: "Үгүй", pronunciation: "Ügüi", english: "No", audio: "audio/Mots/lesson 1/no.mp3" },
        { mongolian: "Тийм", pronunciation: "Tiim", english: "Yes", audio: "audio/Mots/lesson 1/yes.mp3" },
        { mongolian: "Сайн", pronunciation: "Sain", english: "Good", audio: "audio/Mots/lesson 1/good.mp3" },
        { mongolian: "Буруу", pronunciation: "Buruu", english: "Wrong", audio: "audio/Mots/lesson 1/wrong.mp3" },
        { mongolian: "Зөв", pronunciation: "Zöv", english: "Correct", audio: "audio/Mots/lesson 1/correct.mp3" },
        { mongolian: "Тавтай морил", pronunciation: "Tavtai moril", english: "Welcome", audio: "audio/Mots/lesson 1/welcome.mp3" },
        { mongolian: "Баяртай", pronunciation: "Bayartai", english: "Goodbye", audio: "audio/Mots/lesson 1/goodbye.mp3" },
        { mongolian: "Уучлаарай", pronunciation: "Uuchlaarai", english: "Sorry", audio: "audio/Mots/lesson 1/sorry.mp3" },
        { mongolian: "Ойлгосон", pronunciation: "Oilgoson", english: "Understood", audio: "audio/Mots/lesson 1/understood.mp3" },
        { mongolian: "Ойлгохгүй", pronunciation: "Oiloghui", english: "I don't understand", audio: "audio/Mots/lesson 1/i_dont_understand.mp3" },
        { mongolian: "Нэр", pronunciation: "Ner", english: "Name", audio: "audio/Mots/lesson 1/name.mp3" },
        { mongolian: "Би", pronunciation: "Bi", english: "I", audio: "audio/Mots/lesson 1/i.mp3" },
        { mongolian: "Чи", pronunciation: "Chi", english: "You", audio: "audio/Mots/lesson 1/you.mp3" },
        { mongolian: "Тэр", pronunciation: "Ter", english: "He/She", audio: "audio/Mots/lesson 1/he_she.mp3" },
        { mongolian: "Бид", pronunciation: "Bid", english: "We", audio: "audio/Mots/lesson 1/we.mp3" },
        { mongolian: "Та", pronunciation: "Ta", english: "Formal 'You'", audio: "audio/Mots/lesson 1/formal_you.mp3" },
        { mongolian: "Яах вэ", pronunciation: "Yaakh ve?", english: "What to do?", audio: "audio/Mots/lesson 1/what_to_do.mp3" }
    ],
    numbers: [
        { mongolian: "Нэг", pronunciation: "Neg", english: "One", audio: "audio/Mots/lesson 2/One.mp3" },
        { mongolian: "Хоёр", pronunciation: "Khoir", english: "Two", audio: "audio/Mots/lesson 2/Two.mp3" },
        { mongolian: "Гурав", pronunciation: "Gurav", english: "Three", audio: "audio/Mots/lesson 2/Three.mp3" },
        { mongolian: "Дөрөв", pronunciation: "Döröv", english: "Four", audio: "audio/Mots/lesson 2/Four.mp3" },
        { mongolian: "Тав", pronunciation: "Tav", english: "Five", audio: "audio/Mots/lesson 2/Five.mp3" },
        { mongolian: "Зургаа", pronunciation: "Zurgaa", english: "Six", audio: "audio/Mots/lesson 2/Six.mp3" },
        { mongolian: "Долоо", pronunciation: "Doloo", english: "Seven", audio: "audio/Mots/lesson 2/Seven.mp3" },
        { mongolian: "Найм", pronunciation: "Naim", english: "Eight", audio: "audio/Mots/lesson 2/Eight.mp3" },
        { mongolian: "Ес", pronunciation: "Yes", english: "Nine", audio: "audio/Mots/lesson 2/Nine.mp3" },
        { mongolian: "Арван", pronunciation: "Arvan", english: "Ten", audio: "audio/Mots/lesson 2/Ten.mp3" },
        { mongolian: "Цаг", pronunciation: "Tsag", english: "Time", audio: "audio/Mots/lesson 2/Time.mp3" },
        { mongolian: "Минут", pronunciation: "Minut", english: "Minute", audio: "audio/Mots/lesson 2/Minute.mp3" },
        { mongolian: "Өглөө", pronunciation: "Öglöö", english: "Morning", audio: "audio/Mots/lesson 2/Morning.mp3" },
        { mongolian: "Өдөр", pronunciation: "Ödör", english: "Day", audio: "audio/Mots/lesson 2/Day.mp3" },
        { mongolian: "Орой", pronunciation: "Oroi", english: "Evening", audio: "audio/Mots/lesson 2/Evening.mp3" },
        { mongolian: "Шөнө", pronunciation: "Shönö", english: "Night", audio: "audio/Mots/lesson 2/Night.mp3" },
        { mongolian: "Хугацаа", pronunciation: "Khugatsaa", english: "Duration", audio: "audio/Mots/lesson 2/Duration.mp3" },
        { mongolian: "Долоо хоног", pronunciation: "Doloo khonog", english: "Week", audio: "audio/Mots/lesson 2/Week.mp3" },
        { mongolian: "Сар", pronunciation: "Sar", english: "Month", audio: "audio/Mots/lesson 2/Month.mp3" },
        { mongolian: "Жил", pronunciation: "Jil", english: "Year", audio: "audio/Mots/lesson 2/Year.mp3" }
    ],
    family: [
        { mongolian: "Аав", pronunciation: "Aav", english: "Father", audio: "audio/Mots/lesson 3/father.m4a" },
        { mongolian: "Ээж", pronunciation: "Eej", english: "Mother", audio: "audio/Mots/lesson 3/mother.m4a" },
        { mongolian: "Ах", pronunciation: "Akh", english: "Older brother", audio: "audio/Mots/lesson 3/older_brother.m4a" },
        { mongolian: "Эгч", pronunciation: "Egch", english: "Older sister", audio: "audio/Mots/lesson 3/older_sister.m4a" },
        { mongolian: "Дүү", pronunciation: "Düü", english: "Younger sibling", audio: "audio/Mots/lesson 3/younger_sibling.m4a" },
        { mongolian: "Хүүхэд", pronunciation: "Khüükhed", english: "Child", audio: "audio/Mots/lesson 3/child.m4a" },
        { mongolian: "Өвөө", pronunciation: "Övöö", english: "Grandfather", audio: "audio/Mots/lesson 3/grandfather.m4a" },
        { mongolian: "Эмээ", pronunciation: "Emee", english: "Grandmother", audio: "audio/Mots/lesson 3/grandmother.m4a" },
        { mongolian: "Нөхөр", pronunciation: "Nökhör", english: "Husband", audio: "audio/Mots/lesson 3/husband.m4a" },
        { mongolian: "Эхнэр", pronunciation: "Ekhner", english: "Wife", audio: "audio/Mots/lesson 3/wife.m4a" },
        { mongolian: "Гэр бүл", pronunciation: "Ger bül", english: "Family", audio: "audio/Mots/lesson 3/family.m4a" },
        { mongolian: "Хүү", pronunciation: "Khüü", english: "Son", audio: "audio/Mots/lesson 3/son.m4a" },
        { mongolian: "Охин", pronunciation: "Okhin", english: "Daughter", audio: "audio/Mots/lesson 3/daughter.m4a" },
        { mongolian: "Хадам", pronunciation: "Khadam", english: "In-law", audio: "audio/Mots/lesson 3/in_law.m4a" },
        { mongolian: "Хамаатан", pronunciation: "Khamaatan", english: "Relative", audio: "audio/Mots/lesson 3/relative.m4a" },
        { mongolian: "Найз", pronunciation: "Naiz", english: "Friend", audio: "audio/Mots/lesson 3/friend.m4a" },
        { mongolian: "Ах дүү ", pronunciation: "Akh düü", english: "Siblings", audio: "audio/Mots/lesson 3/siblings.m4a" },
        { mongolian: "Хүүгийн", pronunciation: "Khüügiin", english: "Male child's", audio: "audio/Mots/lesson 3/male_childs.m4a" },
        { mongolian: "Охины", pronunciation: "Okhiny", english: "Female child's", audio: "audio/Mots/lesson 3/female_childs.m4a" },
        { mongolian: "Гэрлэлт", pronunciation: "Gerleet", english: "Mariage", audio: "audio/Mots/lesson 3/mariage.m4a" },
    ],
    food: [
        { mongolian: "Хоол", pronunciation: "Khol", english: "Food", audio: "audio/Mots/lesson 4/food.mp3" },
        { mongolian: "Ус", pronunciation: "Us", english: "Water", audio: "audio/Mots/lesson 4/water.mp3" },
        { mongolian: "Сүү", pronunciation: "Süü", english: "Milk", audio: "audio/Mots/lesson 4/milk.mp3" },
        { mongolian: "Цай", pronunciation: "Tsai", english: "Tea", audio: "audio/Mots/lesson 4/tea.mp3" },
        { mongolian: "Кофе", pronunciation: "Kofe", english: "Coffee", audio: "audio/Mots/lesson 4/coffee.mp3" },
        { mongolian: "Талх", pronunciation: "Talkh", english: "Bread", audio: "audio/Mots/lesson 4/bread.mp3" },
        { mongolian: "Будаа", pronunciation: "Budaa", english: "Rice", audio: "audio/Mots/lesson 4/rice.mp3" },
        { mongolian: "Гоймон", pronunciation: "Goimon", english: "Noodles", audio: "audio/Mots/lesson 4/noodles.mp3" },
        { mongolian: "Мах", pronunciation: "Makh", english: "Meat", audio: "audio/Mots/lesson 4/meat.mp3" },
        { mongolian: "Хонины мах", pronunciation: "Khoniny makh", english: "Mutton", audio: "audio/Mots/lesson 4/mutton.mp3" },
        { mongolian: "Үхрийн мах", pronunciation: "Ükhriin makh", english: "Beef", audio: "audio/Mots/lesson 4/beef.mp3" },
        { mongolian: "Тахианы мах", pronunciation: "Takhiiny makh", english: "Chicken", audio: "audio/Mots/lesson 4/chicken.mp3" },
        { mongolian: "Загас", pronunciation: "Zagas", english: "Fish", audio: "audio/Mots/lesson 4/fish.mp3" },
        { mongolian: "Жимс", pronunciation: "Jims", english: "Fruit", audio: "audio/Mots/lesson 4/fruit.mp3" },
        { mongolian: "Ногоо", pronunciation: "Nogoo", english: "Vegetables", audio: "audio/Mots/lesson 4/vegetables.mp3" },
        { mongolian: "Чихэр", pronunciation: "Chikher", english: "Candy", audio: "audio/Mots/lesson 4/candy.mp3" },
        { mongolian: "Жигнэмэг", pronunciation: "Jignemeg", english: "Biscuit", audio: "audio/Mots/lesson 4/biscuit.mp3" },
        { mongolian: "Өндөг", pronunciation: "Öndög", english: "Egg", audio: "audio/Mots/lesson 4/egg.mp3" },
        { mongolian: "Шөл", pronunciation: "Shöl", english: "Soup", audio: "audio/Mots/lesson 4/soup.mp3" },
        { mongolian: "Халуун", pronunciation: "Khaluun", english: "Hot", audio: "audio/Mots/lesson 4/hot.mp3" }
    ],
    colors: [
        { mongolian: "Улаан", pronunciation: "Ulaan", english: "Red", audio: "audio/Mots/lesson 5/red.mp3" },
        { mongolian: "Цэнхэр", pronunciation: "Tsenkher", english: "Blue", audio: "audio/Mots/lesson 5/blue.mp3" },
        { mongolian: "Ногоон", pronunciation: "Nogoon", english: "Green", audio: "audio/Mots/lesson 5/green.mp3" },
        { mongolian: "Шар", pronunciation: "Shar", english: "Yellow", audio: "audio/Mots/lesson 5/yellow.mp3" },
        { mongolian: "Хар", pronunciation: "Khar", english: "Black", audio: "audio/Mots/lesson 5/black.mp3" },
        { mongolian: "Цагаан", pronunciation: "Tsagaan", english: "White", audio: "audio/Mots/lesson 5/white.mp3" },
        { mongolian: "Хүрэн", pronunciation: "Khüren", english: "Brown", audio: "audio/Mots/lesson 5/brown.mp3" },
        { mongolian: "Саарал", pronunciation: "Saaral", english: "Gray", audio: "audio/Mots/lesson 5/gray.mp3" },
        { mongolian: "Ягаан", pronunciation: "Yagaan", english: "Pink", audio: "audio/Mots/lesson 5/pink.mp3" },
        { mongolian: "Нил ягаан", pronunciation: "Nil yagaan", english: "Purple", audio: "audio/Mots/lesson 5/purple.mp3" },
        { mongolian: "Улбар шар", pronunciation: "Ulbar shar", english: "Orange", audio: "audio/Mots/lesson 5/orange.mp3" },
        { mongolian: "Цайвар", pronunciation: "Tsaiwar", english: "Light", audio: "audio/Mots/lesson 5/light.mp3" },
        { mongolian: "Бараан", pronunciation: "Baraan", english: "Dark", audio: "audio/Mots/lesson 5/dark.mp3" },
        { mongolian: "Тод", pronunciation: "Tod", english: "Bright", audio: "audio/Mots/lesson 5/bright.mp3" },
        { mongolian: "Бүдгэрсэн", pronunciation: "Büdgersen", english: "Faded", audio: "audio/Mots/lesson 5/faded.mp3" },
        { mongolian: "Хурц", pronunciation: "Khurts", english: "Vivid", audio: "audio/Mots/lesson 5/vivid.mp3" },
        { mongolian: "Сүүдэртэй", pronunciation: "Süüdertei", english: "Shadowed", audio: "audio/Mots/lesson 5/shadowed.mp3" },
        { mongolian: "Гэгээлэг", pronunciation: "Gegeelekh", english: "Sunny", audio: "audio/Mots/lesson 5/sunny.mp3" },
        { mongolian: "Ясархаг", pronunciation: "Yasarkhag", english: "Pale", audio: "audio/Mots/lesson 5/pale.mp3" },
        { mongolian: "Үлгэрийн", pronunciation: "Ülgeriin", english: "Pastel", audio: "audio/Mots/lesson 5/pastel.mp3" }
    ],
    nature: [
        { mongolian: "Тэнгэр", pronunciation: "Tenger", english: "Sky", audio: "audio/Mots/lesson 6/Тэнгэр.mp3" },
        { mongolian: "Нар", pronunciation: "Nar", english: "Sun", audio: "audio/Mots/lesson 6/Нар.mp3" },
        { mongolian: "Сар", pronunciation: "Sar", english: "Moon", audio: "audio/Mots/lesson 6/Сар.mp3" },
        { mongolian: "Од", pronunciation: "Od", english: "Star", audio: "audio/Mots/lesson 6/Од.mp3" },
        { mongolian: "Ус", pronunciation: "Us", english: "Water", audio: "audio/Mots/lesson 6/Ус.mp3" },
        { mongolian: "Цас", pronunciation: "Tsas", english: "Snow", audio: "audio/Mots/lesson 6/Цас.mp3" },
        { mongolian: "Бороо", pronunciation: "Boroo", english: "Rain", audio: "audio/Mots/lesson 6/Бороо.mp3" },
        { mongolian: "Салхи", pronunciation: "Salkhi", english: "Wind", audio: "audio/Motslesson 6/Салхи.mp3" },
        { mongolian: "Гол", pronunciation: "Gol", english: "River", audio: "audio/Mots/lesson 6/Гол.mp3" },
        { mongolian: "Нуур", pronunciation: "Nuur", english: "Lake", audio: "audio/Mots/lesson 6/Нуур.mp3" },
        { mongolian: "Уул", pronunciation: "Uul", english: "Mountain", audio: "audio/Mots/lesson 6/Уул.mp3" },
        { mongolian: "Тал", pronunciation: "Tal", english: "Plain", audio: "audio/Mots/lesson 6/Тал.mp3" },
        { mongolian: "Ой", pronunciation: "Oi", english: "Forest", audio: "audio/Mots/lesson 6/Ой.mp3" },
        { mongolian: "Элс", pronunciation: "Els", english: "Sand", audio: "audio/Mots/lesson 6/Элс.mp3" },
        { mongolian: "Хад", pronunciation: "Khad", english: "Rock", audio: "audio/Mots/lesson 6/Хад.mp3" },
        { mongolian: "Цэцэг", pronunciation: "Tsetseg", english: "Flower", audio: "audio/Mots/lesson 6/Цэцэг.mp3" },
        { mongolian: "Мод", pronunciation: "Mod", english: "Tree", audio: "audio/Mots/lesson 6/Мод.mp3" },
        { mongolian: "Навч", pronunciation: "Navch", english: "Leaf", audio: "audio/Mots/lesson 6/Навч.mp3" },
        { mongolian: "Хөрс", pronunciation: "Khörs", english: "Soil", audio: "audio/Mots/lesson 6/Хөрс.mp3" },
        { mongolian: "Амьтан", pronunciation: "Am'tan", english: "Animal", audio: "audio/Mots/lesson 6/Амьтан.mp3" }
    ],


    transport: [
        { mongolian: "Машин", pronunciation: "Mashin", english: "Car", audio: "audio/Mots/lesson 7/Машин.mp3" },
        { mongolian: "Унадаг дугуй", pronunciation: "Unadag dugui", english: "Bicycle", audio: "audio/Mots/lesson 7/Унадаг дугуй.mp3" },
        { mongolian: "Автобус", pronunciation: "Avtobus", english: "Bus", audio: "audio/Mots/lesson 7/Автобус.mp3" },
        { mongolian: "Галт тэрэг", pronunciation: "Galt tereg", english: "Train", audio: "audio/Mots/lesson 7/Галт тэрэг.mp3" },
        { mongolian: "Нисэх онгоц", pronunciation: "Nisekh ongots", english: "Airplane", audio: "audio/Mots/lesson 7/Нисэх онгоц.mp3" },
        { mongolian: "Завь", pronunciation: "Zav", english: "Boat", audio: "audio/Mots/lesson 7/Завь.mp3" },
        { mongolian: "Такси", pronunciation: "Taksi", english: "Taxi", audio: "audio/Mots/lesson 7/Такси.mp3" },
        { mongolian: "Метро", pronunciation: "Metro", english: "Metro", audio: "audio/Mots/lesson 7/Метро.mp3" },
        { mongolian: "Мотоцикл", pronunciation: "Motsikl", english: "Motorcycle", audio: "audio/Mots/lesson 7/Мотоцикл.mp3" },
        { mongolian: "Зам", pronunciation: "Zam", english: "Road", audio: "audio/Mots/lesson 7/Зам.mp3" },
        { mongolian: "Тасалбар", pronunciation: "Tasalkhar", english: "Ticket", audio: "audio/Mots/lesson 7/Тасалбар.mp3" },
        { mongolian: "Зогсоол", pronunciation: "Zogsool", english: "Stop", audio: "audio/Mots/lesson 7/Зогсоол.mp3" },
        { mongolian: "Жолооч", pronunciation: "Jolooch", english: "Driver", audio: "audio/Mots/lesson 7/Жолооч.mp3" },
        { mongolian: "Суудал", pronunciation: "Soodal", english: "Seat", audio: "audio/Mots/lesson 7/Суудал.mp3" },
        { mongolian: "Гарах", pronunciation: "Garkh", english: "Exit", audio: "audio/Mots/lesson 7/Гарах.mp3" },
        { mongolian: "Орох", pronunciation: "Orokh", english: "Entrance", audio: "audio/Mots/lesson 7/Орох.mp3" },
        { mongolian: "Бараан ачаа", pronunciation: "Baraan achaa", english: "Luggage", audio: "audio/Mots/lesson 7/Бараан ачаа.mp3" },
        { mongolian: "Аюулгүй", pronunciation: "Ayulgüi", english: "Safe", audio: "audio/Mots/lesson 7/Аюулгүй.mp3" },
        { mongolian: "Түргэн", pronunciation: "Türgen", english: "Fast", audio: "audio/Mots/lesson 7/Түргэн.mp3" },
        { mongolian: "Удаан", pronunciation: "Udaan", english: "Slow", audio: "audio/Mots/lesson 7/Удаан.mp3" }
    ],
    shopping: [
        { mongolian: "Дэлгүүр", pronunciation: "Delgüür", english: "Shop", audio: "audio/Mots/lesson 8/Дэлгүүр.mp3" },
        { mongolian: "Үнэтэй", pronunciation: "Üntei", english: "Expensive", audio: "audio/Mots/lesson 8/Үнэтэй.mp3" },
        { mongolian: "Хямд", pronunciation: "Khyamd", english: "Cheap", audio: "audio/Mots/lesson 8/Хямд.mp3" },
        { mongolian: "Мөнгө", pronunciation: "Möngö", english: "Money", audio: "audio/Mots/lesson 8/Мөнгө.mp3" },
        { mongolian: "Төлбөр", pronunciation: "Tölbör", english: "Payment", audio: "audio/Mots/lesson 8/Төлбөр.mp3" },
        { mongolian: "Бэлэн мөнгө", pronunciation: "Belen möngö", english: "Cash", audio: "audio/Mots/lesson 8/Бэлэн мөнгө.mp3" },
        { mongolian: "Карт", pronunciation: "Kart", english: "Card", audio: "audio/Mots/lesson 8/Карт.mp3" },
        { mongolian: "Бараа", pronunciation: "Baraa", english: "Goods", audio: "audio/Mots/lesson 8/Бараа.mp3" },
        { mongolian: "Хэрэгтэй", pronunciation: "Kheregtei", english: "Necessary", audio: "audio/Mots/lesson 8/Хэрэгтэй.mp3" },
        { mongolian: "Хэрэггүй", pronunciation: "Khereggüi", english: "Not necessary", audio: "audio/Mots/lesson 8/Хэрэггүй.mp3" },
        { mongolian: "Дүн", pronunciation: "Dün", english: "Total", audio: "audio/Mots/lesson 8/Дүн.mp3" },
        { mongolian: "Хямдрал", pronunciation: "Khyamral", english: "Sale", audio: "audio/Mots/lesson 8/Хямдрал.mp3" },
        { mongolian: "Тунгалаг", pronunciation: "Tungalag", english: "Transparent", audio: "audio/Mots/lesson 8/Тунгалаг.mp3" },
        { mongolian: "Нэр", pronunciation: "Ner", english: "Brand", audio: "audio/Mots/lesson 8/Нэр.mp3" },
        { mongolian: "Захиалга", pronunciation: "Zakhiagaa", english: "Order", audio: "audio/Mots/lesson 8/Захиалга.mp3" },
        { mongolian: "Хүргэлт", pronunciation: "Khürgelt", english: "Delivery", audio: "audio/Mots/lesson 8/Хүргэлт.mp3" },
        { mongolian: "Сав баглаа", pronunciation: "Sav baglaa", english: "Packaging", audio: "audio/Mots/lesson 8/Сав баглаа.mp3" },
        { mongolian: "Шинэ", pronunciation: "Shine", english: "New", audio: "audio/Mots/lesson 8/Шинэ.mp3" },
        { mongolian: "Хуучин", pronunciation: "Khuuchin", english: "Old", audio: "audio/Mots/lesson 8/Хуучин.mp3" },
        { mongolian: "Бүтээгдэхүүн", pronunciation: "Bütedekhüün", english: "Product", audio: "audio/Mots/lesson 8/Бүтээгдэхүүн.mp3" }
    ],
    weather: [
        { mongolian: "Дулаан", pronunciation: "Dulaan", english: "Warm", audio: "audio/Mots/lesson 9/Дулаан.mp3" },
        { mongolian: "Хүйтэн", pronunciation: "Khüiten", english: "Cold", audio: "audio/Mots/lesson 9/Хүйтэн.mp3" },
        { mongolian: "Халуун", pronunciation: "Khaluun", english: "Hot", audio: "audio/Mots/lesson 9/Халуун.mp3" },
        { mongolian: "Сэрүүн", pronunciation: "Serüün", english: "Cool", audio: "audio/Mots/lesson 9/Сэрүүн.mp3" },
        { mongolian: "Салхи", pronunciation: "Salkhi", english: "Windy", audio: "audio/Mots/lesson 9/Салхи.mp3" },
        { mongolian: "Бороотой", pronunciation: "Borootoi", english: "Rainy", audio: "audio/Mots/lesson 9/Бороотой.mp3" },
        { mongolian: "Цастай", pronunciation: "Tsastai", english: "Snowy", audio: "audio/Mots/lesson 9/Цастай.mp3" },
        { mongolian: "Нарлаг", pronunciation: "Narlag", english: "Sunny", audio: "audio/Mots/lesson 9/Нарлаг.mp3" },
        { mongolian: "Үүлтэй", pronunciation: "Üültei", english: "Cloudy", audio: "audio/Mots/lesson 9/Үүлтэй.mp3" },
        { mongolian: "Багавтар", pronunciation: "Bagavtar", english: "Mild", audio: "audio/Mots/lesson 9/Багавтар.mp3" },
        { mongolian: "Аадар", pronunciation: "Aadar", english: "Storm", audio: "audio/Mots/lesson 9/Аадар.mp3" },
        { mongolian: "Шороон шуурга", pronunciation: "Shoroon shuurg", english: "Sandstorm", audio: "audio/Mots/lesson 9/Шороон шуурга.mp3" },
        { mongolian: "Даралт", pronunciation: "Dral'lt", english: "Pressure", audio: "audio/Mots/lesson 9/Даралт.mp3" },
        { mongolian: "Чийгтэй", pronunciation: "Chiigtei", english: "Humid", audio: "audio/Mots/lesson 9/Чийгтэй.mp3" },
        { mongolian: "Чийггүй", pronunciation: "Chiiggüi", english: "Dry", audio: "audio/Mots/lesson 9/Чийггүй.mp3" },
        { mongolian: "Сүүдэр", pronunciation: "Süder", english: "Shade", audio: "audio/Mots/lesson 9/Сүүдэр.mp3" },
        { mongolian: "Хүчтэй", pronunciation: "Khüchtei", english: "Strong", audio: "audio/Mots/lesson 9/Хүчтэй.mp3" },
        { mongolian: "Хөнгөн", pronunciation: "Khöngön", english: "Light", audio: "audio/Mots/lesson 9/Хөнгөн.mp3" },
        { mongolian: "Өдөр", pronunciation: "Ödör", english: "Daytime", audio: "audio/Mots/lesson 9/Өдөр.mp3" },
        { mongolian: "Шөнө", pronunciation: "Shönö", english: "Nighttime", audio: "audio/Mots/lesson 9/Шөнө.mp3" }
    ],
    activities: [
        { mongolian: "Босох", pronunciation: "Bosokh", english: "Wake up", audio: "audio/Mots/lesson 10/Босох.mp3" },
        { mongolian: "Унтах", pronunciation: "Untakh", english: "Sleep", audio: "audio/Mots/lesson 10/Унтах.mp3" },
        { mongolian: "Идэх", pronunciation: "Idekh", english: "Eat", audio: "audio/Mots/lesson 10/Идэх.mp3" },
        { mongolian: "Уух", pronunciation: "Uukh", english: "Drink", audio: "audio/Mots/lesson 10/Уух.mp3" },
        { mongolian: "Ажлын", pronunciation: "Ajlin", english: "Work", audio: "audio/Mots/lesson 10/Ажлын.mp3" },
        { mongolian: "Хичээл", pronunciation: "Khiichil", english: "Study", audio: "audio/Mots/lesson 10/Хичээл.mp3" },
        { mongolian: "Тоглох", pronunciation: "Toglokh", english: "Play", audio: "audio/Mots/lesson 10/Тоглох.mp3" },
        { mongolian: "Явах", pronunciation: "Yavakh", english: "Go", audio: "audio/Mots/lesson 10/Явах.mp3" },
        { mongolian: "Ирэх", pronunciation: "Irekh", english: "Come", audio: "audio/Mots/lesson 10/Ирэх.mp3" },
        { mongolian: "Үзэх", pronunciation: "Üzekh", english: "See", audio: "audio/Mots/lesson 10/Үзэх.mp3" },
        { mongolian: "Сонсох", pronunciation: "Sonsoh", english: "Hear", audio: "audio/Mots/lesson 10/Сонсох.mp3" },
        { mongolian: "Бичих", pronunciation: "Bichikh", english: "Write", audio: "audio/Mots/lesson 10/Бичих.mp3" },
        { mongolian: "Унших", pronunciation: "Unshikh", english: "Read", audio: "audio/Mots/lesson 10/Унших.mp3" },
        { mongolian: "Харах", pronunciation: "Kharakh", english: "Watch", audio: "audio/Mots/lesson 10/Харах.mp3" },
        { mongolian: "Зураг", pronunciation: "Zurag", english: "Draw", audio: "audio/Mots/lesson 10/Зураг.mp3" },
        { mongolian: "Угаах", pronunciation: "Ugaakh", english: "Wash", audio: "audio/Mots/lesson 10/Угаах.mp3" },
        { mongolian: "Хийх", pronunciation: "Khiikh", english: "Do", audio: "audio/Mots/lesson 10/Хийх.mp3" },
        { mongolian: "Амрах", pronunciation: "Amrakh", english: "Rest", audio: "audio/Mots/lesson 10/Амрах.mp3" },
        { mongolian: "Хувцаслах", pronunciation: "Khuvtsaslah", english: "Get dressed", audio: "audio/Mots/lesson 10/Хувцаслах.mp3" },
        { mongolian: "Яриа", pronunciation: "Yaria", english: "Speak", audio: "audio/Mots/lesson 10/Яриа.mp3" }
    ],
    body: [
        { mongolian: "Толгой", pronunciation: "tolgoi", english: "Head", audio: "audio/Mots/lesson 11/Толгой.mp3" },
        { mongolian: "Нүд", pronunciation: "nüd", english: "Eye", audio: "audio/Mots/lesson 11/Нүд.mp3" },
        { mongolian: "Чих", pronunciation: "chikh", english: "Ear", audio: "audio/Mots/lesson 11/Чих.mp3" },
        { mongolian: "Хамар", pronunciation: "khamar", english: "Nose", audio: "audio/Mots/lesson 11/Хамар.mp3" },
        { mongolian: "Ам", pronunciation: "am", english: "Mouth", audio: "audio/Mots/lesson 11/Ам.mp3" },
        { mongolian: "Шүд", pronunciation: "shüd", english: "Tooth", audio: "audio/Mots/lesson 11/Шүд.mp3" },
        { mongolian: "Хүзүү", pronunciation: "khüzüü", english: "Neck", audio: "audio/Mots/lesson 11/Хүзүү.mp3" },
        { mongolian: "Гар", pronunciation: "gar", english: "Hand", audio: "audio/Mots/lesson 11/Гар.mp3" },
        { mongolian: "Хөл", pronunciation: "khöl", english: "Leg", audio: "audio/Mots/lesson 11/Хөл.mp3" },
        { mongolian: "Хуруу", pronunciation: "khuruu", english: "Finger", audio: "audio/Mots/lesson 11/Хуруу.mp3" },
        { mongolian: "Өвдөг", pronunciation: "övdög", english: "Knee", audio: "audio/Mots/lesson 11/Өвдөг.mp3" },
        { mongolian: "Цээж", pronunciation: "tseej", english: "Chest", audio: "audio/Mots/lesson 11/Цээж.mp3" },
        { mongolian: "Нуруу", pronunciation: "nuruu", english: "Back", audio: "audio/Mots/lesson 11/Нуруу.mp3" },
        { mongolian: "Хурууны хумс", pronunciation: "khuruuny khums", english: "Fingernail", audio: "audio/Mots/lesson 11/Хурууны хумс.mp3" },
        { mongolian: "Арьс", pronunciation: "arys", english: "Skin", audio: "audio/Mots/lesson 11/Арьс.mp3" },
        { mongolian: "Үс", pronunciation: "üs", english: "Hair", audio: "audio/Mots/lesson 11/Үс.mp3" },
        { mongolian: "Зүрх", pronunciation: "zürkh", english: "Heart", audio: "audio/Mots/lesson 11/Зүрх.mp3" },
        { mongolian: "Ходоод", pronunciation: "khodood", english: "Stomach", audio: "audio/Mots/lesson 11/Ходоод.mp3" },
        { mongolian: "Мөч", pronunciation: "möch", english: "Limb", audio: "audio/Mots/lesson 11/Мөч.mp3" },
        { mongolian: "Нүүр", pronunciation: "nüür", english: "Face", audio: "audio/Mots/lesson 11/Нүүр.mp3" }
    ],
    emotions: [
        { mongolian: "Аз жаргал", pronunciation: "az jargal", english: "Happiness", audio: "audio/Mots/lesson 12/Аз жаргал.mp3" },
        { mongolian: "Уур", pronunciation: "uur", english: "Anger", audio: "audio/Mots/lesson 12/Уур.mp3" },
        { mongolian: "Гуниг", pronunciation: "gunig", english: "Sadness", audio: "audio/Mots/lesson 12/Гуниг.mp3" },
        { mongolian: "Айдас", pronunciation: "aidas", english: "Fear", audio: "audio/Mots/lesson 12/Айдас.mp3" },
        { mongolian: "Сэтгэл хөдлөл", pronunciation: "setgel khödlel", english: "Emotion", audio: "audio/Mots/lesson 12/Сэтгэл хөдлөл.mp3" },
        { mongolian: "Итгэл", pronunciation: "itgel", english: "Trust", audio: "audio/Mots/lesson 12/Итгэл.mp3" },
        { mongolian: "Эелдэг", pronunciation: "eeldeg", english: "Kindness", audio: "audio/Mots/lesson 12/Эелдэг.mp3" },
        { mongolian: "Шунал", pronunciation: "shunal", english: "Greed", audio: "audio/Mots/lesson 12/Шунал.mp3" },
        { mongolian: "Өшөө авалт", pronunciation: "öshöö avalt", english: "Revenge", audio: "audio/Mots/lesson 12/Өшөө авалт.mp3" },
        { mongolian: "Талархал", pronunciation: "talarhal", english: "Gratitude", audio: "audio/Mots/lesson 12/Талархал.mp3" },
        { mongolian: "Бахархал", pronunciation: "bakharkhal", english: "Pride", audio: "audio/Mots/lesson 12/Бахархал.mp3" },
        { mongolian: "Шок", pronunciation: "shok", english: "Shock", audio: "audio/Mots/lesson 12/Шок.mp3" },
        { mongolian: "Хайр", pronunciation: "khair", english: "Love", audio: "audio/Mots/lesson 12/Хайр.mp3" },
        { mongolian: "Харамсал", pronunciation: "kharamsal", english: "Regret", audio: "audio/Mots/lesson 12/Харамсал.mp3" },
        { mongolian: "Инээд", pronunciation: "ineed", english: "Laughter", audio: "audio/Mots/lesson 12/Инээд.mp3" },
        { mongolian: "Урам хугарах", pronunciation: "uram khugarakh", english: "Disappointment", audio: "audio/Mots/lesson 12/Урам хугарах.mp3" },
        { mongolian: "Эвгүйцэх", pronunciation: "evgüitsekh", english: "Embarrassment", audio: "audio/Mots/lesson 12/Эвгүйцэх.mp3" },
        { mongolian: "Баяр", pronunciation: "bayar", english: "Joy", audio: "audio/Mots/lesson 12/Баяр.mp3" },
        { mongolian: "Гайхширал", pronunciation: "gaikhshiral", english: "Surprise", audio: "audio/Mots/lesson 12/Гайхширал.mp3" },
        { mongolian: "Тайван", pronunciation: "taivan", english: "Calm", audio: "audio/Mots/lesson 12/Тайван.mp3" }
    ],
    occupations: [
        { mongolian: "Эмч", pronunciation: "emch", english: "Doctor", audio: "audio/Mots/lesson 13/Эмч.mp3" },
        { mongolian: "Сувилагч", pronunciation: "suvilagch", english: "Nurse", audio: "audio/Mots/lesson 13/Сувилагч.mp3" },
        { mongolian: "Багш", pronunciation: "bagsh", english: "Teacher", audio: "audio/Mots/lesson 13/Багш.mp3" },
        { mongolian: "Оюутан", pronunciation: "oyutan", english: "Student", audio: "audio/Mots/lesson 13/Оюутан.mp3" },
        { mongolian: "Жолооч", pronunciation: "jolooch", english: "Driver", audio: "audio/Mots/lesson 13/Жолооч.mp3" },
        { mongolian: "Худалдагч", pronunciation: "khudaldagch", english: "Seller", audio: "audio/Mots/lesson 13/Худалдагч.mp3" },
        { mongolian: "Цагдаа", pronunciation: "tsagdaa", english: "Police officer", audio: "audio/Mots/lesson 13/Цагдаа.mp3" },
        { mongolian: "Гал сөнөөгч", pronunciation: "gal söngööch", english: "Firefighter", audio: "audio/Mots/lesson 13/Гал сөнөөгч.mp3" },
        { mongolian: "Инженер", pronunciation: "injener", english: "Engineer", audio: "audio/Mots/lesson 13/Инженер.mp3" },
        { mongolian: "Хуульч", pronunciation: "khuulich", english: "Lawyer", audio: "audio/Mots/lesson 13/Хуульч.mp3" },
        { mongolian: "Фермер", pronunciation: "fermer", english: "Farmer", audio: "audio/Mots/lesson 13/Фермер.mp3" },
        { mongolian: "Зураач", pronunciation: "zuraach", english: "Artist", audio: "audio/Mots/lesson 13/Зураач.mp3" },
        { mongolian: "Жүжигчин", pronunciation: "jüjigchin", english: "Actor", audio: "audio/Mots/lesson 13/Жүжигчин.mp3" },
        { mongolian: "Даяанч", pronunciation: "dayanch", english: "Monk", audio: "audio/Mots/lesson 13/Даяанч.mp3" },
        { mongolian: "Нягтлан бодогч", pronunciation: "nyagtlan bodogch", english: "Accountant", audio: "audio/Mots/lesson 13/Нягтлан бодогч.mp3" },
        { mongolian: "Згвар зохион бүтээгч", pronunciation: "zagvar zohion büüteegch", english: "Designer", audio: "audio/Mots/lesson 13/Загвар зохион бүтээгч.mp3" },
        { mongolian: "Программист", pronunciation: "programmist", english: "Programmer", audio: "audio/Mots/lesson 13/Программист.mp3" },
        { mongolian: "Орчуулагч", pronunciation: "orchuulagch", english: "Translator", audio: "audio/Mots/lesson 13/Орчуулагч.mp3" },
        { mongolian: "Журналист", pronunciation: "jurnalist", english: "Journalist", audio: "audio/Mots/lesson 13/Журналист.mp3" },
        { mongolian: "Удирдагч", pronunciation: "udirdagch", english: "Leader", audio: "audio/Mots/lesson 13/Удирдагч.mp3" }
    ],
    clothing: [
        { mongolian: "Гутал", pronunciation: "gutal", english: "Shoes", audio: "audio/Mots/lesson 14/Гутал.mp3" },
        { mongolian: "Цамц", pronunciation: "tsamts", english: "Shirt", audio: "audio/Mots/lesson 14/Цамц.mp3" },
        { mongolian: "Өмд", pronunciation: "ömd", english: "Pants", audio: "audio/Mots/lesson 14/Өмд.mp3" },
        { mongolian: "Юбка", pronunciation: "yubka", english: "Skirt", audio: "audio/Mots/lesson 14/Юбка.mp3" },
        { mongolian: "Даашинз", pronunciation: "daashinz", english: "Dress", audio: "audio/Mots/lesson 14/Даашинз.mp3" },
        { mongolian: "Малгай", pronunciation: "malgai", english: "Hat", audio: "audio/Mots/lesson 14/Малгай.mp3" },
        { mongolian: "роолт", pronunciation: "oroolt", english: "Scarf", audio: "audio/Mots/lesson 14/роолт.mp3" },
        { mongolian: "Бээлий", pronunciation: "beelii", english: "Gloves", audio: "audio/Mots/lesson 14/Бээлий.mp3" },
        { mongolian: "Куртка", pronunciation: "kurtka", english: "Jacket", audio: "audio/Mots/lesson 14/Куртка.mp3" },
        { mongolian: "Цув", pronunciation: "tsuv", english: "Coat", audio: "audio/Mots/lesson 14/Цув.mp3" },
        { mongolian: "Туфль", pronunciation: "tufl", english: "Heels", audio: "audio/Mots/lesson 14/Туфль.mp3" },
        { mongolian: "Дотуур хувцас", pronunciation: "dotuur khuvtsas", english: "Underwear", audio: "audio/Mots/lesson 14/Дотуур хувцас.mp3" },
        { mongolian: "Бүс", pronunciation: "büs", english: "Belt", audio: "audio/Mots/lesson 14/Бүс.mp3" },
        { mongolian: "Оймс", pronunciation: "oyms", english: "Socks", audio: "audio/Mots/lesson 14/Оймс.mp3" },
        { mongolian: "Цүнх", pronunciation: "tsünkh", english: "Bag", audio: "audio/Mots/lesson 14/Цүнх.mp3" },
        { mongolian: "Нүдний шил", pronunciation: "nüdnij shil", english: "Glasses", audio: "audio/Mots/lesson 14/Нүдний шил.mp3" },
        { mongolian: "Зүүлт", pronunciation: "züült", english: "Necklace", audio: "audio/Mots/lesson 14/Зүүлт.mp3" },
        { mongolian: "Бугуйвч", pronunciation: "buguivch", english: "Bracelet", audio: "audio/Mots/lesson 14/Бугуйвч.mp3" },
        { mongolian: "Цаг", pronunciation: "tsag", english: "Watch", audio: "audio/Mots/lesson 14/Цаг.mp3" },
        { mongolian: "Жижиг цүнх", pronunciation: "jijig tsünkh", english: "Purse", audio: "audio/Mots/lesson 14/Жижиг цүн.mp3" }
    ],
    animals: [
        { mongolian: "Нохой", pronunciation: "nokhoi", english: "Dog", audio: "audio/Mots/lesson 15/Нохой.mp3" },
        { mongolian: "Муур", pronunciation: "müür", english: "Cat", audio: "audio/Mots/lesson 15/Муур.mp3" },
        { mongolian: "Морь", pronunciation: "mor'", english: "Horse", audio: "audio/Mots/lesson 15/Морь.mp3" },
        { mongolian: "Үхэр", pronunciation: "ükher", english: "Cow", audio: "audio/Mots/lesson 15/Үхэр.mp3" },
        { mongolian: "Хонь", pronunciation: "khon'", english: "Sheep", audio: "audio/Mots/lesson 15/Хонь.mp3" },
        { mongolian: "Ямаа", pronunciation: "yamaa", english: "Goat", audio: "audio/Mots/lesson 15/Ямаа.mp3" },
        { mongolian: "Гүүхай", pronunciation: "gakhai", english: "Pig", audio: "audio/Mots/lesson 15/Гахай.mp3" },
        { mongolian: "Тахиа", pronunciation: "takhiia", english: "Chicken", audio: "audio/Mots/lesson 15/Тахиа.mp3" },
        { mongolian: "Нугас", pronunciation: "nugas", english: "Duck", audio: "audio/Mots/lesson 15/Нугас.mp3" },
        { mongolian: "Загас", pronunciation: "zagas", english: "Fish", audio: "audio/Mots/lesson 15/Загас.mp3" },
        { mongolian: "Чоно", pronunciation: "chono", english: "Wolf", audio: "audio/Mots/lesson 15/Чоно.mp3" },
        { mongolian: "Тэмээ", pronunciation: "temee", english: "Camel", audio: "audio/Mots/lesson 15/Тэмээ.mp3" },
        { mongolian: "Баавгай", pronunciation: "baavgai", english: "Bear", audio: "audio/Mots/lesson 15/Баавгай.mp3" },
        { mongolian: "Арслан", pronunciation: "arslan", english: "Lion", audio: "audio/Mots/lesson 15/Арслан.mp3" },
        { mongolian: "Заан", pronunciation: "zaan", english: "Elephant", audio: "audio/Mots/lesson 15/Заан.mp3" },
        { mongolian: "Матар", pronunciation: "matar", english: "Crocodile", audio: "audio/Mots/lesson 15/Матар.mp3" },
        { mongolian: "Туулай", pronunciation: "tuulai", english: "Rabbit", audio: "audio/Mots/lesson 15/Туулай.mp3" },
        { mongolian: "Хулгана", pronunciation: "khulgana", english: "Mouse", audio: "audio/Mots/lesson 15/Хулгана.mp3" },
        { mongolian: "Шувуу", pronunciation: "shuvuu", english: "Bird", audio: "audio/Mots/lesson 15/Шувуу.mp3" },
        { mongolian: "Бурхнаас эрсэн загас", pronunciation: "burkhnaas ersen zagas", english: "Goldfish", audio: "audio/Mots/lesson 15/Бурхнаас эрсэн загас.mp3" }
    ],
    technology: [
        { mongolian: "Гар утас", pronunciation: "gar utas", english: "Mobile phone", audio: "audio/Mots/lesson 16/Гар утас.mp3" },
        { mongolian: "Компьютер", pronunciation: "kompyuter", english: "Computer", audio: "audio/Mots/lesson 16/Компьютер.mp3" },
        { mongolian: "Дэлгэц", pronunciation: "delgets", english: "Screen", audio: "audio/Mots/lesson 16/Дэлгэц.mp3" },
        { mongolian: "Зурагт", pronunciation: "zuragt", english: "Television", audio: "audio/Mots/lesson 16/Зурагт.mp3" },
        { mongolian: "Камер", pronunciation: "kamer", english: "Camera", audio: "audio/Mots/lesson 16/Камер.mp3" },
        { mongolian: "Чихэвч", pronunciation: "chikhevch", english: "Headphones", audio: "audio/Mots/lesson 16/Чихэвч.mp3" },
        { mongolian: "Микрофон", pronunciation: "mikrofon", english: "Microphone", audio: "audio/Mots/lesson 16/Микрофон.mp3" },
        { mongolian: "Тоглоом", pronunciation: "togloom", english: "Game", audio: "audio/Mots/lesson 16/Тоглоом.mp3" },
        { mongolian: "Интернет", pronunciation: "internet", english: "Internet", audio: "audio/Mots/lesson 16/Интернет.mp3" },
        { mongolian: "Зай", pronunciation: "zai", english: "Battery", audio: "audio/Mots/lesson 16/Зай.mp3" },
        { mongolian: "Гар хулгана", pronunciation: "gar khulgana", english: "Mouse (computer)", audio: "audio/Mots/lesson 16/Гар хулгана.mp3" },
        { mongolian: "Принтер", pronunciation: "printer", english: "Printer", audio: "audio/Mots/lesson 16/Принтер.mp3" },
        { mongolian: "Гэрэл зургийн аппарат", pronunciation: "gerel zuragiin apparat", english: "Photo camera", audio: "audio/Mots/lesson 16/Гэрэл зургийн аппарат.mp3" },
        { mongolian: "Хард диск", pronunciation: "khard disk", english: "Hard drive", audio: "audio/Mots/lesson 16/Хард диск.mp3" },
        { mongolian: "Гар", pronunciation: "gar", english: "Keyboard", audio: "audio/Mots/lesson 16/Гар.mp3" },
        { mongolian: "Ухаалаг цаг", pronunciation: "ukhaalag tsag", english: "Smartwatch", audio: "audio/Mots/lesson 16/Ухаалаг цаг.mp3" },
        { mongolian: "Хэвлэгч", pronunciation: "khevlegch", english: "Scanner", audio: "audio/Mots/lesson 16/Хэвлэгч.mp3" },
        { mongolian: "Таблет", pronunciation: "tablet", english: "Tablet", audio: "audio/Mots/lesson 16/Таблет.mp3" },
        { mongolian: "Ухаалаг утас", pronunciation: "ukhaalag utas", english: "Smartphone", audio: "audio/Mots/lesson 16/Ухаалаг утас.mp3" },
        { mongolian: "Чип", pronunciation: "chip", english: "Chip", audio: "audio/Mots/lesson 16/Чип.mp3" }
    ],
    hobbies: [
        { mongolian: "Ном унших", pronunciation: "nom unshikh", english: "Reading", audio: "audio/Mots/lesson 17/Ном унших.mp3" },
        { mongolian: "Зураг зурах", pronunciation: "zurag zurakh", english: "Drawing", audio: "audio/Mots/lesson 17/Зураг зурах.mp3" },
        { mongolian: "Бичих", pronunciation: "bichikh", english: "Writing", audio: "audio/Mots/lesson 17/Бичих.mp3" },
        { mongolian: "Тоглох", pronunciation: "toglokh", english: "Playing", audio: "audio/Mots/lesson 17/Тоглох.mp3" },
        { mongolian: "Дуучлах", pronunciation: "duuchlakh", english: "Singing", audio: "audio/Mots/lesson 17/Дуучлах.mp3" },
        { mongolian: "Бүжиглэх", pronunciation: "büjiglekh", english: "Dancing", audio: "audio/Mots/lesson 17/Бүжиглэх.mp3" },
        { mongolian: "Жүжиглэх", pronunciation: "jüjiglekh", english: "Acting", audio: "audio/Mots/lesson 17/Жүжиглэх.mp3" },
        { mongolian: "Спорт тоглох", pronunciation: "sport toglogh", english: "Playing sports", audio: "audio/Mots/lesson 17/Спорт тоглох.mp3" },
        { mongolian: "Дуулах", pronunciation: "duulakh", english: "Singing", audio: "audio/Mots/lesson 17/Дуулах.mp3" },
        { mongolian: "Дугуй унах", pronunciation: "dugui unakh", english: "Cycling", audio: "audio/Mots/lesson 17/Дугуй унах.mp3" },
        { mongolian: "Кино үзэх", pronunciation: "kino üzekh", english: "Watching movies", audio: "audio/Mots/lesson 17/Кино үзэх.mp3" },
        { mongolian: "Загасчлах", pronunciation: "zagaschlakh", english: "Fishing", audio: "audio/Mots/lesson 17/Загасчлах.mp3" },
        { mongolian: "Нэхэх", pronunciation: "nekekh", english: "Knitting", audio: "audio/Mots/lesson 17/Нэхэх.mp3" },
        { mongolian: "Зайрмаг идэх", pronunciation: "zaimrag idekh", english: "Eating ice cream", audio: "audio/Mots/lesson 17/Зайрмаг идэх.mp3" },
        { mongolian: "Бялуу хийх", pronunciation: "byaluu khiikh", english: "Baking cakes", audio: "audio/Mots/lesson 17/Бялуу хийх.mp3" },
        { mongolian: "Зохион бичих", pronunciation: "zokhion bichikh", english: "Composing", audio: "audio/Mots/lesson 17/Зохион бичих.mp3" },
        { mongolian: "Хэл сурах", pronunciation: "khel surakh", english: "Learning languages", audio: "audio/Mots/lesson 17/Хэл сурах.mp3" },
        { mongolian: "Зураг авах", pronunciation: "zurag avakh", english: "Taking photos", audio: "audio/Mots/lesson 17/Зураг авах.mp3" },
        { mongolian: "Дуран харах", pronunciation: "duran kharakh", english: "Stargazing", audio: "audio/Mots/lesson 17/Дуран харах.mp3" },
        { mongolian: "Усан санд сэлэх", pronunciation: "usan sand selekh", english: "Swimming", audio: "audio/Mots/lesson 17/Усан санд сэлэх.mp3" }
    ],
    travel: [
        { mongolian: "Онгоц", pronunciation: "ongots", english: "Plane", audio: "audio/Mots/lesson 18/Онгоц.mp3" },
        { mongolian: "Галт тэрэг", pronunciation: "galt tereg", english: "Train", audio: "audio/Mots/lesson 18/Галт тэрэг.mp3" },
        { mongolian: "Хөлөг онгоц", pronunciation: "khölög ongots", english: "Ship", audio: "audio/Mots/lesson 18/Хөлөг онгоц.mp3" },
        { mongolian: "Нисэх буудал", pronunciation: "niskh buudal", english: "Airport", audio: "audio/Mots/lesson 18/Нисэх буудал.mp3" },
        { mongolian: "Зочид буудал", pronunciation: "zochid buudal", english: "Hotel", audio: "audio/Mots/lesson 18/Зочид буудал.mp3" },
        { mongolian: "Гэр", pronunciation: "ger", english: "Ger (traditional tent)", audio: "audio/Mots/lesson 18/Гэр.mp3" },
        { mongolian: "Хоолны газар", pronunciation: "khoolni gazar", english: "Restaurant", audio: "audio/Mots/lesson 18/Хоолны газар.mp3" },
        { mongolian: "Газрын зураг", pronunciation: "gazarin zurag", english: "Map", audio: "audio/Mots/lesson 18/Газрын зураг.mp3" },
        { mongolian: "Аялал", pronunciation: "ayalal", english: "Travel", audio: "audio/Mots/lesson 18/Аялал.mp3" },
        { mongolian: "Хил", pronunciation: "khil", english: "Border", audio: "audio/Mots/lesson 18/Хил.mp3" },
        { mongolian: "Виз", pronunciation: "viz", english: "Visa", audio: "audio/Mots/lesson 18/Виз.mp3" },
        { mongolian: "Буудал", pronunciation: "buudal", english: "Stop", audio: "audio/Mots/lesson 18/Буудал.mp3" },
        { mongolian: "Хөтөч", pronunciation: "khötöch", english: "Guide", audio: "audio/Mots/lesson 18/Хөтөч.mp3" },
        { mongolian: "Жуулчин", pronunciation: "juulchin", english: "Tourist", audio: "audio/Mots/lesson 18/Жуулчин.mp3" },
        { mongolian: "Аялал жуулчлал", pronunciation: "ayalal juulchlal", english: "Tourism", audio: "audio/Mots/lesson 18/Аялал жуулчлал.mp3" },
        { mongolian: "Зам", pronunciation: "zam", english: "Road", audio: "audio/Mots/lesson 18/Зам.mp3" },
        { mongolian: "Цүнх", pronunciation: "tsünkh", english: "Luggage", audio: "audio/Mots/lesson 18/Цүнх.mp3" },
        { mongolian: "Газрын тос", pronunciation: "gazriin tos", english: "Petrol", audio: "audio/Mots/lesson 18/Газрын тос.mp3" },
        { mongolian: "Галт тэрэгний буудал", pronunciation: "galt teregnii buudal", english: "Train station", audio: "audio/Mots/lesson 18/Галт тэрэгний буудал.mp3" },
        { mongolian: "Картаар төлөх", pronunciation: "kartaar tölökh", english: "Pay by card", audio: "audio/Mots/lesson 18/Картаар төлөх.mp3" }
    ],
    shapes: [
        { mongolian: "Тойрог", pronunciation: "toirog", english: "Circle", audio: "audio/Mots/lesson 19/Тойрог.mp3" },
        { mongolian: "Дөрвөлжин", pronunciation: "dörvöljin", english: "Square", audio: "audio/Mots/lesson 19/Дөрвөлжин.mp3" },
        { mongolian: "Гурвалжин", pronunciation: "gurwaljin", english: "Triangle", audio: "audio/Mots/lesson 19/Гурвалжин.mp3" },
        { mongolian: "Урт", pronunciation: "urt", english: "Long", audio: "audio/Mots/lesson 19/Урт.mp3" },
        { mongolian: "Богино", pronunciation: "bogino", english: "Short", audio: "audio/Mots/lesson 19/Богино.mp3" },
        { mongolian: "Өргөн", pronunciation: "örgön", english: "Wide", audio: "audio/Mots/lesson 19/Өргөн.mp3" },
        { mongolian: "Нарийн", pronunciation: "nariin", english: "Narrow", audio: "audio/Mots/lesson 19/Нарийн.mp3" },
        { mongolian: "Том", pronunciation: "tom", english: "Big", audio: "audio/Mots/lesson 19/Том.mp3" },
        { mongolian: "Жижиг", pronunciation: "jijig", english: "Small", audio: "audio/Mots/lesson 19/Жижиг.mp3" },
        { mongolian: "Дундаж", pronunciation: "dundaj", english: "Average", audio: "audio/Mots/lesson 19/Дундаж.mp3" },
        { mongolian: "Дугуй", pronunciation: "dugui", english: "Round", audio: "audio/Mots/lesson 19/Дугуй.mp3" },
        { mongolian: "Хавтгай", pronunciation: "khawtgai", english: "Flat", audio: "audio/Mots/lesson 19/Хавтгай.mp3" },
        { mongolian: "Гүдгэр", pronunciation: "güdger", english: "Convex", audio: "audio/Mots/lesson 19/Гүдгэр.mp3" },
        { mongolian: "Хөндлөн", pronunciation: "khöndlön", english: "Horizontal", audio: "audio/Mots/lesson 19/Хөндлөн.mp3" },
        { mongolian: "Босоо", pronunciation: "bosoo", english: "Vertical", audio: "audio/Mots/lesson 19/Босоо.mp3" },
        { mongolian: "Тэгш", pronunciation: "tegsh", english: "Equal", audio: "audio/Mots/lesson 19/Тэгш.mp3" },
        { mongolian: "Шулуун", pronunciation: "shuluun", english: "Straight", audio: "audio/Mots/lesson 19/Шулуун.mp3" },
        { mongolian: "Муруй", pronunciation: "murui", english: "Curved", audio: "audio/Mots/lesson 19/Муруй.mp3" },
        { mongolian: "Өнцөг", pronunciation: "öntsög", english: "Angle", audio: "audio/Mots/lesson 19/Өнцөг.mp3" },
        { mongolian: "Тэгш өнцөгт", pronunciation: "tegsh öntsögt", english: "Rectangle", audio: "audio/Mots/lesson 19/Тэгш өнцөгт.mp3" }
    ],
    verbs: [
        { mongolian: "Ярих", pronunciation: "yarikh", english: "To speak", audio: "audio/Mots/lesson 20/Ярих.mp3" },
        { mongolian: "Сонсох", pronunciation: "sonsoh", english: "To listen", audio: "audio/Mots/lesson 20/Сонсох.mp3" },
        { mongolian: "Харах", pronunciation: "kharakh", english: "To look", audio: "audio/Mots/lesson 20/Харах.mp3" },
        { mongolian: "Бичих", pronunciation: "bichikh", english: "To write", audio: "audio/Mots/lesson 20/Бичих.mp3" },
        { mongolian: "Унших", pronunciation: "unshikh", english: "To read", audio: "audio/Mots/lesson 20/Унших.mp3" },
        { mongolian: "Босох", pronunciation: "bosokh", english: "To get up", audio: "audio/Mots/lesson 20/Босох.mp3" },
        { mongolian: "Сууцгаах", pronunciation: "suutsgaakh", english: "To sit", audio: "audio/Mots/lesson 20/Сууцгаах.mp3" },
        { mongolian: "Идэх", pronunciation: "idekh", english: "To eat", audio: "audio/Mots/lesson 20/Идэх.mp3" },
        { mongolian: "Уух", pronunciation: "uukh", english: "To drink", audio: "audio/Mots/lesson 20/Уух.mp3" },
        { mongolian: "Инээх", pronunciation: "inee", english: "To smile", audio: "audio/Mots/lesson 20/Инээх.mp3" },
        { mongolian: "Унтах", pronunciation: "untakh", english: "To sleep", audio: "audio/Mots/lesson 20/Унтах.mp3" },
        { mongolian: "Тоглох", pronunciation: "toglokh", english: "To play", audio: "audio/Mots/lesson 20/Тоглох.mp3" },
        { mongolian: "Хийх", pronunciation: "khiikh", english: "To do", audio: "audio/Mots/lesson 20/Хийх.mp3" },
        { mongolian: "Туслах", pronunciation: "tuslakh", english: "To help", audio: "audio/Mots/lesson 20/Туслах.mp3" },
        { mongolian: "Хөөх", pronunciation: "khökh", english: "To chase", audio: "audio/Mots/lesson 20/Хөөх.mp3" },
        { mongolian: "Амрах", pronunciation: "amrakh", english: "To rest", audio: "audio/Mots/lesson 20/Амрах.mp3" },
        { mongolian: "Сурах", pronunciation: "surakh", english: "To learn", audio: "audio/Mots/lesson 20/Сурах.mp3" },
        { mongolian: "Заах", pronunciation: "zaakh", english: "To teach", audio: "audio/Mots/lesson 20/Заах.mp3" },
        { mongolian: "Авах", pronunciation: "avakh", english: "To take", audio: "audio/Mots/lesson 20/Авах.mp3" },
        { mongolian: "Өгөх", pronunciation: "ögökh", english: "To give", audio: "audio/Mots/lesson 20/Өгөх.mp3" }
    ]
}; 
